---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: networking
spec:
  interval: 5m

  chart:
    spec:
      # renovate: registryUrl=https://helm.traefik.io/traefik
      chart: traefik
      version: 10.9.1
      sourceRef:
        kind: HelmRepository
        name: traefik-charts
        namespace: flux-system
      interval: 5m

  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace

  values:
    image:
      name: ghcr.io/k8s-at-home/traefik

    deployment:
      kind: Deployment
      replicas: 1

    service:
      enabled: true
      type: LoadBalancer
      spec:
        loadBalancerIP: "${METALLB_TRAEFIK_ADDR}"
        externalTrafficPolicy: Local

    logs:
      general:
        format: json
        level: DEBUG
      access:
        enabled: true
        format: json

    ingressClass:
      enabled: true
      isDefaultClass: true
      fallbackApiVersion: v1

    ingressRoute:
      dashboard:
        enabled: false

    globalArguments:
      - "--api.insecure=true"
      - "--serverstransport.insecureskipverify=true"
      - "--providers.kubernetesingress.ingressclass=traefik"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.entryPoint=metrics"

    additionalArguments:
      - "--certificatesresolvers.letsencrypt.acme.email=${SECRET_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
      - "--certificatesResolvers.letsencrypt.acme.tlsChallenge=true"
      - "--providers.kubernetesingress.ingressendpoint.ip=${METALLB_TRAEFIK_ADDR}"
      - "--providers.kubernetesingress.allowexternalnameservices=true"
      - "--providers.kubernetescrd.allowexternalnameservices=true"

    ports:
      traefik:
        expose: true
      ssh:
        expose: true
        exposedPort: 22
        port: 7999
        protocol: TCP
      web:
        redirectTo: websecure
      websecure:
        tls:
          enabled: true
          options: "default"
      metrics:
        port: 8082
        expose: true
        exposedPort: 8082

    tlsOptions:
      default:
        minVersion: VersionTLS12
        maxVersion: VersionTLS13
#        sniStrict: true

    pilot:
      enabled: false

    experimental:
      plugins:
        enabled: false

    # resources:
    #   requests:
    #     memory: 100Mi
    #     cpu: 500m
    #   limits:
    #     memory: 500Mi
