# yamllint disable
# objstore.yml: |-
#     type: s3
#     config:
#       bucket:
#       endpoint:
#       access_key:
#       secret_key:
#       insecure: true
apiVersion: v1
kind: Secret
metadata:
    name: thanos-object-store
    namespace: monitoring
stringData:
    objstore.yml: ENC[AES256_GCM,data:fgwL3o+JOPPRBJPaUZ+XVruAnTDlO/8/eV+DjYv+CJNcKT1kl9R844OLsZS9wzl+C2nbOqRqnryw/y2hWzJKYakruCPrbnrjzJgQByzPidUl+1PwGwA9n9OZu14cATjM6bGXfnehK6I0i+j6AdweqXamf3I3O8AgI7gpnKUHyaXHqncVtcrJxTOCAihwNuP/tgTv9c3ZZAxuHlY7fB6NY7arpw==,iv:nG4YA0ri4HjGKELNicOjmGwxpRek/aByH4PTa7BXWbA=,tag:WoL/I/4AKWo6ZJGcdKNFkA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gpkhe6ap5xgmnrgjsc0vcxldp6g33gag3ul8ar2l5dvn32ccdunqpwdcuj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2MDN0Ykdpc2JtZkxCdWlC
            d3EyWUZXUVpSM00wekQydWVxZ05MZ09QSlhrCklNd2ovR1JxVFYwYVNUdTF3QXEw
            UmFRdXRlZHMzZ1pZSjdDQjgxaGI5TVEKLS0tIGZoRHlaendlczFqaXZpbE1KbmV6
            Z3dDdXVubHdTK0JZdDVBOGpiWXRjK2MKDW7uHTV6zKOiCkwOMOQp+frFRbzUBU/b
            OMAiNjjFhZ9l+UFyHlBkCYQYqkTTpybDTCP/F81umo6d+4/KOTTl1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-06T18:50:25Z"
    mac: ENC[AES256_GCM,data:2RRVRyp9MA4QZddx/FJv1flaIaWxxL7FGAbylRMWEeMYapPeBCeHQEMdRIoAK7s/MEUVuOEDCwSqMJAL5dm5uTBZn6cuZzjT/qfSHYVrlFHN//z1Xhj8pboH5Rq5W3zYhkPOE2vecOPCV1vceOns6LZxTCNr6btCgsPV2oZtsWQ=,iv:7M0r5DK6+Sz2st1go1pSi8Mt1H9bSzkrTKGge1S1Zb4=,tag:1VTS4ail23b33fU0Xyjgfw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
