apiVersion: v1
kind: Secret
metadata:
    name: bitbucket
    namespace: development
stringData:
    admin-username: ENC[AES256_GCM,data:+kF++p2t3g==,iv:OikxJrJLdNYZGhggEH+OIcyxpVRp56ppLIsF9+L6E/w=,tag:hYVJ0BX1PeyHQrDBvC01uQ==,type:str]
    admin-password: ENC[AES256_GCM,data:Ulb1OR1wPLzRRYuVTO8=,iv:cysl1VZj6evh54Ca5xd1jcT6ZPdK1Pj//ZaOywmW+y8=,tag:FGEG5Sgb2bOt76T0vZZ5Zg==,type:str]
    admin-displayName: ENC[AES256_GCM,data:L9VT/moVcuVyq0LTdg==,iv:RnyV6UVhNdTOBAOFJaKUbp6ZLLXg1K7HsBLfWhxw5k8=,tag:wr0oviNMcLGrq3H9ET/wLA==,type:str]
    admin-emailAddress: ENC[AES256_GCM,data:f52Zb/2sUOc6DhAOfVC3rucYzeBffMg=,iv:wmW5NOTeuQt951Ao6ugXj1pz3zGp7NftcvPJwooJ2YQ=,tag:faH+eEBrCnTehvRLH08WCQ==,type:str]
    database-username: ENC[AES256_GCM,data:0nkUVfDYs40=,iv:1HddGSFExOTu1ONIGk6i5xYNdLd2HeyujOsTm/k6U4g=,tag:rmAKu/W+GKT3snI+eNi/dg==,type:str]
    database-password: ENC[AES256_GCM,data:vX+ZqroHmw==,iv:hXaQlzIKSv0PfwVolEZKwd78dvtW3Zk7tXv4YaiLqUk=,tag:G7Vc2ye0pJTyyfOtjHFX1w==,type:str]
    license-key: ENC[AES256_GCM,data:51J8KWF2hCjIUhKxb37zo3cFZK6C2X9HQqqUuk14aPOo7eD+MvPZL4Q/DrWuQ0fw+DIrNmgtbFra5Ue3KHrUdV5OeyuEXTpkVOzRMKmWqovRyTdVNZFnJi6fUlv7gJLvWhOG6S85pC6g8Y7lOqGJDkZnQx97l3XZ+hdwkspEM1wNCTNzrF+wfLo2HqXEP6JmIF0b1fxXQkiyCK0SYwD7itT4EbnH62KlJiLbT9c0WIgKieD2LQ9vi51p2Kb250vJEQ0dSsHNdFzHXkeP3vIZzLLHVtzAtFOx5WJbMjaBYE5rOD4jADKuKdaY4B0lcDeTvY02m9UJyKDBXYXFmQGmxJab/GMSXvYDDTYZOxtCa117YS/6k/Yor5I0SXM+Cg/VKMFIPRt7X+lpC8MaRGSLFRIZuMmG0XJw983QvmiAv4o3xY2Bba7bNiOZJIRtXGSySwmEt/PvZHbt/QvN7Ah69bF3644p7t5Xvhkyq38N0biprSiFASQ5KLeZyS2ICHfjtnHYf7lq2CoRG+zlfmyabzU09Hqkf4F6DcnCYKOMw92C793HASw9JuGQe/0VL0CxFfe89xGTxud1TkyPqgAv3KNbyjKMbXkcf37G48ZvVK2tl/1ebNtPb4+uOJlbFqVaGFO8jJvQDq3udXsqwK7eqk+PJFEqIPwMzeT6REaxb5PEJCGf8F5zyrs+5PUuBd5yDoguSbdGE7QidyKJ5cePiuDPeffbMQGKxKfgcevdCG1BKD+aVcW9XjglzGTjzJK7cVvevqHkxsZ3dFpXUQMMIUD1alv02/1feZXMViZcEbqQDukRPCWl9RpmqO+nxPIMhX1nWTSGp26amvU+5qPznru48OpPfK9MeIkzI4zCPeQZ5/2BoQ==,iv:fSASW2DRbvsITDbSDB+Sg5AupKqrWjUhDpM7ZKVqdys=,tag:3vz48kHzOyDtmsDkyiYYkA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gpkhe6ap5xgmnrgjsc0vcxldp6g33gag3ul8ar2l5dvn32ccdunqpwdcuj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMm1aUEFRaXdhSWFwVzBM
            SkI1blJxbGdveDFtSGpxelhJUFhoYnFCZncwCk5xa1JaZVlRV0xQMExRTitybElN
            b3NkV0tUK0dMRm1tTFpVUmorQmFHVjgKLS0tIEFJdEE5K3dNenZoM3VJZ3VFazJx
            Q3NhaVFBQkF0YTVCdm9OMW54Q05YWGMKcYVbzQB5hNgbqzfWVtOaM6J+JIpx4gzS
            cSXrEvhE4Z+6oJFh0f6mlq29ToRB6iEVjseHScjJ5pID3zPMlNCwfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-06T18:50:25Z"
    mac: ENC[AES256_GCM,data:sT0kizeqUq8YiCwIxxQBZ4CtjPSAzpQfcX4zQvzRuE2I3YZb4S7oAvj9ajLFEDYG+VjoA623lSdSmRENyz+Ox+GsTtoP0cOeU14tp+bQAj77hXtrVEL76FlSwCvzhj5T/R80GkQvU6J7kU9gUeHSNtiZQ9YJcvZorG+F6yPFrP0=,iv:muc01U/HtgG98jVluy0qyjsbTxf2lA9o3tQfhh0s8ls=,tag:/03EGy5Z/zyGSKUsr54Lhw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
