---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: goldilocks
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: goldilocks
      version: 6.1.4
      sourceRef:
        kind: HelmRepository
        name: fairwinds-charts
        namespace: flux-system
      interval: 5m
  values:
    vpa:
      enabled: true

    controller:
      flags:
        on-by-default: false
        exclude-namespaces: kube-system

    dashboard:
      replicaCount: 1
      ingress:
        ingressClassName: "traefik"
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          cert-manager.io/issue-temporary-certificate: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "memory"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-rfc1918@kubernetescrd"
        hosts:
          - host: goldilocks.${SECRET_DOMAIN}
            paths:
              - path: /
                type: ImplementationSpecific
        tls:
          - hosts:
              - goldilocks.${SECRET_DOMAIN}
            secretName: "goldilocks-tls"

    resources:
      limits:
        memory: 500Mi
