---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: trow
  namespace: development
spec:
  interval: 5m
  chart:
    spec:
      chart: trow
      version: 0.3.4
      sourceRef:
        kind: HelmRepository
        name: trow-charts
        namespace: flux-system
      interval: 5m
  values:
    # image:
    #   repository: atlassian/bitbucket
    #   tag: 7.20.0

    trow:
      domain: registry.rfc826.com

    service:
      type: ClusterIP

    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        cert-manager.io/issue-temporary-certificate: "true"
        hajimari.io/enable: "true"
        hajimari.io/icon: "file-code"
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      hosts:
        - paths: ['/']
          host: trow.${SECRET_DOMAIN}
      tls:
        - secretName: trow-tls
          hosts:
            - trow.${SECRET_DOMAIN}

      # resources: {}
        # We usually recommend not to specify default resources and to leave this as a conscious
        # choice for the user. This also increases chances charts run on environments with little
        # resources, such as Minikube. If you do want to specify resources, uncomment the following
        # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
        # limits:
        #   cpu: 100m
        #   memory: 128Mi
        # requests:
        #   cpu: 100m
        #   memory: 128Mi

    volumeClaim:
      persistentVolumeClaim:
        claimName: trow

    podAnnotations:
      backup.velero.io/backup-volumes: "trow"
      secret.reloader.stakater.com/reload: "trow"

  valuesFrom:
    - kind: Secret
      name: trow
      valuesKey: user
      targetPath: trow.user
      optional: false
    - kind: Secret
      name: trow
      valuesKey: password
      targetPath: trow.password
      optional: false
