---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: transmission
  namespace: downloads
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: transmission
      version: 8.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/transmission
      tag: latest

    env:
      TRANSMISSION_RPC_AUTHENTICATION_REQUIRED: "true"
      TRANSMISSION_DOWNLOAD_DIR: /media/downloads/complete
      TRANSMISSION_INCOMPLETE_DIR: /media/downloads/incomplete
      TZ: "Europe/Amsterdam"
      TRANSMISSION_RPC_USERNAME:
        valueFrom:
          secretKeyRef:
            name: transmission
            key: TRANSMISSION_RPC_USERNAME
      TRANSMISSION_RPC_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: transmission
            key: TRANSMISSION_RPC_PASSWORD

    podSecurityContext:
      fsGroup: 0
      # runAsNonRoot: true
      runAsUser: 0
      runAsGroup: 0
      fsGroupChangePolicy: "Always"
      # supplementalGroups:
      #   - 100

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          cert-manager.io/issue-temporary-certificate: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "file-download-outline"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: download.${SECRET_DOMAIN}
            paths:
              - path: /transmission
                pathType: Prefix
        tls:
          - hosts:
              - download.${SECRET_DOMAIN}
            secretName: "download-tls"

    persistence:
      # config:
      #   enabled: true
      #   existingClaim: transmission
      media:
        enabled: true
        existingClaim: downloads
      shared:
        enabled: true
        type: emptyDir
        mountPath: /shared

    addons:

      vpn:
        enabled: true
        type: openvpn

        openvpn:
          authSecret: openvpn-auth

        env:
          FIREWALL: 'on'
          ROUTE_1: ${NETWORK_K8S_CLUSTER_CIDR}
          ROUTE_2: ${NETWORK_K8S_SERVICE_CIDR}
          ROUTE_3: ${NETWORK_SERVER_CIDR}
          VPNPORT_1: "9091"

        configFileSecret: openvpn-config

        scripts:
          up: |-
            #!/bin/bash
            /etc/openvpn/up.sh
            echo "connected" > /shared/vpnstatus

          down: |-
            #!/bin/bash
            /etc/openvpn/down.sh
            echo "disconnected" > /shared/vpnstatus
