---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://grafana.github.io/helm-charts
      chart: loki
      version: 2.8.1
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/loki
    # ingress:
    #   enabled: true
    #   # ingressClassName: "traefik"
    #   annotations:
    #     kubernetes.io/ingress.class: traefik
    #     cert-manager.io/cluster-issuer: "letsencrypt-production"
    #     cert-manager.io/issue-temporary-certificate: "true"
    #     # hajimari.io/enable: "true"
    #     # hajimari.io/icon: "movie-open-play"
    #     traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    #     # cert-manager.io/cluster-issuer: letsencrypt-production
    #     # # external-dns.alpha.kubernetes.io/target: ingress.${INGRESS_DOMAIN}
    #     # traefik.ingress.kubernetes.io/router.entrypoints: websecure
    #     traefik.ingress.kubernetes.io/router.middlewares: "networking-rfc1918@kubernetescrd"
    #   hosts:
    #     - host: "loki.${SECRET_DOMAIN}"
    #       paths:
    #         - /
    #   tls:
    #     - hosts:
    #         - "loki.${SECRET_DOMAIN}"
    #       secretName: loki-tls

    config:
      storage_config:
        aws:
          bucketnames: loki
          endpoint: "s3.rfc826.com"
          s3forcepathstyle: true
        boltdb_shipper:
          active_index_directory: /data/loki/index
          cache_location: /data/loki/index_cache
          resync_interval: 5s
          shared_store: s3
        alertmanager_url: http://prometheus-alertmanager:9093

    persistence:
      enabled: false

    serviceMonitor:
      enabled: true

  valuesFrom:
    - kind: Secret
      name: loki-s3
      valuesKey: minio_access_key
      targetPath: config.storage_config.aws.access_key_id
      optional: false
    - kind: Secret
      name: loki-s3
      valuesKey: minio_secret_key
      targetPath: config.storage_config.aws.secret_access_key
      optional: false
