# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:264tdl/kqbfk1g==,iv:GQpImg+SB1FEh47CKVO5K1ahMe0h3FwEnNbTUYdH+bI=,tag:SqQ3t3rXgtK3EvR0O9hDrA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gpkhe6ap5xgmnrgjsc0vcxldp6g33gag3ul8ar2l5dvn32ccdunqpwdcuj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrTGZsaFRDTVp5YmJRaWlD
            SU1pek45VkFVLzRkdzZZMXVhdG16NFhqd1YwClJLaFEyalhmUGtYbmZVTlIxYW51
            cmNFZzBDV0VrT0F3SmtjYW5STVVyZkEKLS0tIDMxUU5FQnFPaHFISnJmelExS2FH
            b3d6YXJBZEgvRUQxVWpOVkd4QW1nQXcKDXcjLnK7il2dn2jo0NS64Zus4aWLTueL
            CbeBCwl7zomo+JnAXF6FeDVu1YLO4b0/fBdYogxRFJC/lZN52Y+ihQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-06T18:50:25Z"
    mac: ENC[AES256_GCM,data:vrk09+38g3ARIfXfFv9t79sinRSL70/rdTg1ts7XWcFsZcvvKkTnxID3m7o/o//U3rQYC8oN2sqDyYAU26a6cEJQTfdlZ2ItbA5UKY+ExnCGLYwwuNstixe4ztdzqF4hzFF/ykli+KfZ0EYrgly3m6hfof3hr+81xZanlXXeQMY=,iv:mrdVMmQ0SgHfQf7QuPaCatoRDGpTJowLsUpEaVqW3UU=,tag:4yvjVJu0jccVkAQDMmXAGA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
