# yamllint disable
# objstore.yml: |-
#     type: s3
#     config:
#       bucket:
#       endpoint:
#       access_key:
#       secret_key:
#       insecure: true
apiVersion: v1
kind: Secret
metadata:
    name: thanos-object-store
    namespace: monitoring
stringData:
    object-store.yaml: ENC[AES256_GCM,data:s/CUIaUETnp4F0/IU8bAH6jJW/BPfxcrFaXl8vMaeJpp/iz7hn4mgAKjBZAlfdl9jmMqN8Biq2mQKj6gdHWT0mrJNVbFFbHcc3NUqJTOw6c8ojbzRBVv1A7gkMyonBOGTwUACPPQJDeOixFkbYD35n7SSQ==,iv:1AXmBXYxtihayPY2UfU64NZDWq+YvJZAkvxe/nWmKI8=,tag:8g1U+tGig4I/L4W0Zfv/cg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-22T13:15:43Z"
    mac: ENC[AES256_GCM,data:u4rSR1nQ3GC+n6gqeq9j7W0/e7UEaNihqZlCaMoD8gB6MrBVpJIn5r2V+qCggl/ZfB3Y0KJY3tlgBAAbR4keG4Z9dilrO6B15Vlq12OPk7G9CV0B2as+vxzpXjxxbIn+j43vcazEY+AJFRbYRthMw+d3w7MXmvIRF0fQGa40wDE=,iv:gy84ly6rt2WW5gLyYzcj2jh1R3GO/JTb/IP3voiLZlc=,tag:/n029yfZ1tkTj7ll88Dj9Q==,type:str]
    pgp:
        - created_at: "2021-11-22T13:15:43Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA452ft8CT80SARAA02t9e0jhcnKRGYkptsYuzCZmbCv/M0AVrmQ904V9/Gll
            du4IgkQBHWoi25EsvZk68iDdJ8ldJj/vJ0o/0AjiAIag8kSdHpJx4q0hZBCMkYUb
            T4bowrk0ZCz5sPESCSLnwIdiIVXjE0f5n8oN6byRApg20nS8/U3Uww5qNIYLyFiD
            HchOEUDqnHUZUHXrcL+LBnIAZOj5F9Dk6Xp9rNFf+c94uwCK80jpnOQmOcVdB4BF
            afpdjV7W1w9gI8tdGU16Q9uyfFvzYxjwBrx+6QQc2HgyWLRclHBwkLjbmtTRg6Mm
            LEk5hI2yAJdnC/AV/lSppY4SXpnU6hYqUsy4jmKu6SKSYwcGxTpa3qR9nShDb7RC
            4gUd+I5b10hk6kGrRhZFV2lHMv9tx/Boh2uoIweHcN53Qj/XDKv1cPm6XycwMdwb
            F+ycp85jc1Vmw7Yi4SRM9R9rj28RBhec8mWNWKojHe5xRMAegXalWxlW3YrvLplc
            cjnqJZfe5kJnQHrS9Nv1DKA/0t+KzXzrndnSy6a8oad5thWhj/hPeRIPu644Gbky
            dgull2g5uimh+l5FelSbm1EnDP9GBdAODd7LWVElWl2B1FE81g9zrKi9eCyk2RhQ
            iCYODnNvWGm7AeTS8CGIiPSREss1kec5wCXoDmlD3CTHccZSKQvRsJeLLDXkps/S
            XgGHuPAjpyTMVXAuyEOz3sHD+USBu8kvxmUK06wiLoxNSWpWGzt7oPBljVJXiqG9
            j1ogaejSXcIFOfrNYKlba94EMWu4r4lSHuVThlzrFq0nowDdHe5NfXY7f4eTBi0=
            =dArP
            -----END PGP MESSAGE-----
          fp: A46BCBE5025D400A71759E6947630974DB001607
        - created_at: "2021-11-22T13:15:43Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAzKiqMukNpUtAQ/+OJnd4ywGopwEupCL2EAWZSh2Zs/3QquREM7CgcGen5cD
            HXWwqkcDJa/QW/mj2vD9Bsk4S6gPnHdU5u3o+JVFYT/vdVYjE0wPvQKBX3Bp00tG
            YAChvlS5uhgGRsKX8nroOEOLOfus1s+XzEwRlgGT9hQhhD9PDADJm4h/QmqD06Oa
            wK09cqGLZ/hAKsE7VEnX62RUkcLOZ1ZWwMZRjt97QHCRvTTNQID7ZQPrDu5tAr6y
            /KkS0q0soJQelQ2E1uwgCrC6aNX/yYuT11x+3Tx2MK8gghyzZqr0ujcBZN+FRXTa
            HLj0Tm6xlBWf1XjgO40r3v/4owgDntYeT0tdyESz1A6pxjIq9KZpxgU5gfMpJcdO
            SRlMIqbS5RKvLiG/7GRJDeZ105O1aSTtSC7vy2mB429Xp7UB49nsOYpQ9VIph1np
            ptwgJ3lE/F+kzyEr38JOg0VPdo+MvOKeIwsI4AdGjb13nHhsRoAGbe41nloWxEpX
            3D/ZVpuadrbRkABqi2pwA4+Y9cvbio+0q+D98eQDU6QgX7bMy3EzZcfTsicrYRC+
            6RHDpQ1S/T63EyeeY4+hb7cUnO2ykgQ9t8WRAMlgQgHuGLNrPYWRk0i2wgxwVSam
            03qNCNp5bZ2ZNkAxm8qQKqDYaZXp/YSOpDNntUj5HeDC1qIjCRuS1RQqlFACLRXS
            XgHRV9yA1r0bz86cy8G9gScJD2JPSoDzNmGS0rohY75N3pPLy+cCRtuQxB+gmFiV
            rrZhKLRAZbj5di1HJvBaLtP3VOa+i72g8TzPJWkLpOzNJm3bpce8CX4rzElNA+A=
            =o/ud
            -----END PGP MESSAGE-----
          fp: 416E502A845A87487EF12661331A5023FC9B89BA
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
