---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blackbox-exporter
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://prometheus-community.github.io/helm-charts
      chart: prometheus-blackbox-exporter
      version: 5.3.1
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: flux-system
      interval: 5m
  values:
    fullnameOverride: blackbox-exporter
    nameOverride: blackbox-exporter
    allowIcmp: true
    secretConfig: false
    config:
      modules:
        icmp:
          prober: icmp
          timeout: 30s
          icmp:
            preferred_ip_protocol: "ip4"
    serviceMonitor:
      enabled: true
      defaults:
        labels:
          release: prometheus
        interval: 30s
        scrapeTimeout: 30s
      targets:
        - name: router
          url: 192.168.2.1
          module: icmp
        - name: worker-node-1
          url: 192.168.2.21
          module: icmp
        - name: control-plane-1
          url: 192.168.2.31
          module: icmp
        - name: control-plane-2
          url: 192.168.2.32
          module: icmp
        - name: control-plane-3
          url: 192.168.2.33
          module: icmp
        # - name: truenas
        #   url: 10.10.0.10
        #   module: icmp
        # - name: hdhomerun
        #   url: 10.10.0.113
        #   module: icmp
