---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rxresume
  namespace: self-hosted
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: openebs-nvme-0
