---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bamboo-agent
  namespace: development
spec:
  interval: 5m
  chart:
    spec:
      chart: bamboo-agent
      version: 1.3.0
      sourceRef:
        kind: HelmRepository
        name: atlassian-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: atlassian/bamboo-agent-base
      tag: 8.1.3

    agent:
      securityToken:
        secretName: bamboo
        secretKey: security-token
      server: bamboo.development.svc.cluster.local

    podAnnotations:
      secret.reloader.stakater.com/reload: "bamboo-agent"
