---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rxresume
  namespace: self-hosted
spec:
  interval: 5m
  chart:
    spec:
      chart: /charts/kah-common/
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: amruthpillai/reactive-resume
      tag: v3

    nameOverride: rxresume

    service:
      main:
        ports:
          http:
            port: 80

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          cert-manager.io/issue-temporary-certificate: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "account-search"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-rfc1918@kubernetescrd"
        hosts:
          - host: cv.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "cv.${SECRET_DOMAIN}"
            secretName: rxresume-tls

    persistence:
      config:
        enabled: true
        existingClaim: rxresume
        mountPath: /usr/share/nginx/html

    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 500Mi

    podAnnotations:
      backup.velero.io/backup-volumes: config
