---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bamboo
  namespace: development
spec:
  interval: 5m
  chart:
    spec:
      chart: bamboo
      version: 1.5.0
      sourceRef:
        kind: HelmRepository
        name: atlassian-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: atlassian/bamboo
      tag: 9.0.0

    database:
      type: 'postgresql'
      url: 'jdbc:postgresql://postgresql.databases.svc.cluster.local:5432/bamboo'
      credentials:
        secretName: bamboo
        usernameSecretKey: database-username
        passwordSecretKey: database-password

    volumes:
      localHome:
        customVolume:
          persistentVolumeClaim:
            claimName: "bamboo-home"
      sharedHome:
        customVolume:
          persistentVolumeClaim:
            claimName: "bamboo-shared"
        nfsPermissionFixer:
          enabled: false

    ingress:
      create: true
      className: "traefik"
      nginx: false
      host: build.${SECRET_DOMAIN}
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        cert-manager.io/issue-temporary-certificate: "true"
        hajimari.io/enable: "true"
        hajimari.io/icon: "progress-check"
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      https: true
      tlsSecretName: bamboo-tls

    bamboo:
      unattendedSetup: true
      license:
        secretName: bamboo
        secretKey: license-key
      sysadminCredentials:
        secretName: bamboo
        usernameSecretKey: admin-username
        passwordSecretKey: admin-password
        displayNameSecretKey: admin-displayName
        emailAddressSecretKey: admin-emailAddress
      securityToken:
        secretName: bamboo
        secretKey: security-token
      disableAgentAuth: true

    podAnnotations:
      backup.velero.io/backup-volumes: "local-home,shared-home"
      secret.reloader.stakater.com/reload: "bamboo"
