apiVersion: v1
kind: Secret
metadata:
    name: filebrowser
    namespace: downloads
stringData:
    FB_USERNAME: ENC[AES256_GCM,data:t2Yk7AZakl34,iv:1eXrGO+xabDN8D1zKIFbbZHRkv4CJty6MghZEu3Jd6Y=,tag:5PyMs5PsRDW06waGck8DsQ==,type:str]
    FB_PASSWORD: ENC[AES256_GCM,data:GY8OvBZ8AFM0/gQqwZHuQjjg59R4Sr0BchTbWwiIFljU8Ajolu1gtTy9q9bk3zbAqyGb35nTYz/KeNeA,iv:oQRvJEm4/mjB1ORRl7fx6GlwQxir+P3/BGpq4Ga8GBA=,tag:U3S7m2B4nli2ib+E7rwa1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-01T15:35:47Z"
    mac: ENC[AES256_GCM,data:tbMrvQ7Kn69AmQBsKxxtJKIhNz9QR7vnBOO1OAKrOyDKyDDcoQuAvy3OSKi6qauyUrCtIefm0e5JN5Bqp9pdX7j7ErDfjjThOfJSeAj6MUppGk8EWJHba59gYKkMBkOtWViIBfgkksSlY2CW3/lOlueHMJecsRb5lo25lDb3WnA=,iv:Rvva1LO2At8v+udjB8E9tFelCM4B154wKB66BFk81y8=,tag:UaxW3LHJMohC6hC8tRhKGg==,type:str]
    pgp:
        - created_at: "2021-11-01T15:35:46Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA452ft8CT80SARAA3XQjpzCO3QUPHH8A8b+Mm/+lBNX8387KRwzgXt30f6eO
            p7unCR0+SivcN98YllZp7YXamzYJh4S3Qso3JFRiOg8FFzVC+fZsx6fSJggM2wDk
            8yHB3sL5kKuXU35BUBjj9bbvDPfJ2ZM7gITvTNI2MYLXgqOlgk8cxp47qPwbqnEm
            p30KKZWit+vIMzjlGHu1iQdVSijznpEbcUHVHTfPnqeD9RXzDrtCQtfxTdkrrPnU
            xt+dZfuODHnBXTG10fqmHqARqRgeCkL8/ZaCO9qXwLQQxwCHmDb0E5aX90fB2ebA
            AgwI8mOCClnWAp9EBlh/HkT7iA4lTeKEVyv5CwX7Cyy5D3YrUtXqh+RP12F6UYVM
            BE79wZj7PedrmdpIvH6Kyx/rl4hnUUE9O7EDXFk7aUPRsQSlIHuq7Q0ijHIdqyUF
            1EsVYXpYX6+ftuQi8WgjV2DjhsQtO2pRC5Ry5OyWfz2uvOYaJl7Y8hOj+eE9Uh32
            AWQ3HzN4m06Fej5MrRSLJusUb7yC9izaqfwxtrFfIw+DtM0Yl+CoqJRtTtYJ3XI2
            COH9E7OrqCcy1b/kqlO4UeDlKVkoraChOXHRdabtS1FCLBZWwFV8fy/rfvDBQ6EJ
            IKVdQGRMhUJeFOe0duU7Lr63v7BFJSyQJy3OqC1l/dW5k6Ew6mF5osjBUHTweM/S
            XgERdwnaVNGXqHdKLu3VFn0wU8v7LxsXNf4pwhxHM1sC3GRYWhOz6ILUAgYiAwu4
            146Bql8FgEQ2CkSS0/h87O+02aUJRmRaI38xZfxK5Ra1xM0Af0Z2+MpWMljjX/E=
            =V6xu
            -----END PGP MESSAGE-----
          fp: A46BCBE5025D400A71759E6947630974DB001607
        - created_at: "2021-11-01T15:35:46Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAzKiqMukNpUtARAAgQj89DZOXt3tT0f+Aph42jQtKQL2XI9GC9mDFMzPM6xA
            gp27LgfnFzwhPXiMeiQwPDU2BoZ9WiEGqMqaGxH2WI96NtXiq6jgrgqkHhqFsH1H
            rnWofCeGGAq2IA7L3VZX3+JLDpdMbXgMWj61hyLF2l4QjRIgF0nqOajEXkFkgVJ9
            ycYfF/Tb0auGRVHRfVvk4iZtisXUZ7qKa0Z1aVunorBfQkVHr/hCHqV15UsPJKM1
            fYGy8NGgt98bPw+XmbKhhZorYHIxHrJESKJnxit3+/LpUUWQMXFjcYUcmN1H+UYO
            uIZoeUj/0lOJXsz38PtmnwiWM4h+3ZBxT6y+IERdrC8oJE0ZTSNfRMXgBBcCDu2u
            cIdYSVmRQQ4rv91btgj/Fe911lzFBdv261GBa3YC8ZuzEy/L7ZfC7y4Ev1vQ11BR
            dmKcJHmixsBF4F/VmcRAdaJSQtlZUhltobeKcJ1tFxbpYxrEM+x78krjNMWd7fU7
            n33sXe+wF34KZlVkYdIYoZ8Vh82WSztVrzsEYshgzcYGfxxoUXrsn7M0nfBg/5Jm
            t2YveTNf6E2WbYbDg3E7KR8MSDjWx9o5j9ubhQ/hlrdaDw2mA6K263bn7+GCXgf8
            f+DAuUvEB64VDl6155+lCdUHI3QoM9ggpWnfCm92bh9OwZx5TxC/qmMjEfdV/gzS
            XgFx67XqmVwoIfZ8zMpbMuuycRNnekgiCSkChbwtGnFZJuPQZ6daRNSt63xaNNaO
            aDKrl0VLIKqdB3uOm3GGso3pWPVp1xe8B1cbfRWoUfTB2aWH+aOHw3ZV6Q91g+Y=
            =OiTS
            -----END PGP MESSAGE-----
          fp: 416E502A845A87487EF12661331A5023FC9B89BA
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
