apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - changedetection-io
  - echo-server
  - ghost
  - hajimari
  - littlelink
  - minio
  # - nextcloud
  - rxresume
  # - syncthing
  - vaultwarden
