---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-storage
  namespace: networking
#  labels:
#    kasten.io/backup-volume: "enabled"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: openebs-hostpath
