apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: bitbucket-ssh
  namespace: development
spec:
  entryPoints:
    - ssh
  routes:
    - match: HostSNI(`*`)
      services:
        - name: bitbucket-ssh
          port: 7999
