# yamllint disable
# objstore.yml: |-
#     type: s3
#     config:
#       bucket:
#       endpoint:
#       access_key:
#       secret_key:
#       insecure: true
apiVersion: v1
kind: Secret
metadata:
    name: thanos-object-store
    namespace: monitoring
stringData:
    objstore.yml: ENC[AES256_GCM,data:f1iHKNhFrcqEDEVmv6XW2jPi12YCew+SG5I9c8Hogs7ztXg504XalkekRL4aqShqRfX916HNd1yxMtADFqa4XfrDwEje8/7bQRIPL6sq1mLtopgA2lAxKchhkckHyAP/m3fRsXAiAQPtHbMwoTqEvn+G5M6q3cHrvGUkR5Kf2+Strf2tby9pT86hNabmS9gdU3MKkaspSKqi4tQYdwGWeueLWw==,iv:XNgoFqbC7f22nhYph2nVzuY32PsVx9UmvxxijZdJB/8=,tag:ixfGfnicfxKIdc7P3jpq3g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gpkhe6ap5xgmnrgjsc0vcxldp6g33gag3ul8ar2l5dvn32ccdunqpwdcuj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkQ0dYdkpEVEc2TldJdGxK
            YVpOV01zaHFEQ2NmTUh6MWkrS2lRamJUWVhVCnR5TjJXMXBBQkJUcUxCdVhBblE2
            bTJiUm8rRFgxM0RJYk13a0g5dEpLanMKLS0tIGJuaEtraENyWm9RTy8vb3c3S0xq
            aENhZlNKZ2owTGNaVkp0Ukd1aXVYcmcKQFD6rghzUW5J2KC1eo0lcCLN9AdRQgpG
            7QsNQWU5SB8vFtPmsLYLzXE4qRuK74+vcneyR2Q0jWr/hHd/jQeiyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-06T18:50:25Z"
    mac: ENC[AES256_GCM,data:+qPwIgWEcL20teyVg4mljGpSN1M1DyAm0dOGxYD4e1tMBrTzbWti21F1ODqaV/8oJdwYG8PfdnjminCkQXwykFb47IT7E2hcXniHNvuz0Yka3+cxmW5MOU9aLRHJcad9fJCGLBvbduhDQYwSAgQW8ea5fzSfmNtT90aOZIalCiA=,iv:OwG/pdyArCONwpf2zHPlBfEFajIugtmNQ53N5SoRKv4=,tag:Ng5rBoCo9LnVxJPqsIZxPQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
