kubernetes:
  children:
    master:
      hosts:
        control-plane-1:
          ansible_host: 192.168.188.81
        control-plane-2:
          ansible_host: 192.168.188.82
        control-plane-3:
          ansible_host: 192.168.188.83
    worker:
      hosts:
        worker-node-1:
          ansible_host: 192.168.188.41