apiVersion: v1
kind: Secret
metadata:
    name: openvpn-auth
    namespace: downloads
stringData:
    VPN_AUTH: ENC[AES256_GCM,data:DQu6p/U4f+nLjGHGd4IFBXKf8BbIFRLeKoF0J6YmwI8xGYk6kvE=,iv:o8DCSJsgT62giTbJunGyT9RgXQHfZgGcy7A03GODoCM=,tag:tCAwiFNu+37YIPdIrn2NZg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gpkhe6ap5xgmnrgjsc0vcxldp6g33gag3ul8ar2l5dvn32ccdunqpwdcuj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1SSt2V2VEZk1Md3lLbXJw
            V0E4OTNzalp4S1dRUy9seTFHclVEQ1dCdVRFCmtHaUYxUDJPSG9tNVM5TFdkd2Fj
            NEdkWENDTnNtSXRhc1BBeDVpWVNVcFUKLS0tIEFsTVpSSGVta3ZpZG1tNWh4L3VM
            MnFNNDZwdE1kaDlxZ3ZLOTc3cjRTUncKHW0RZmwr2lb5GJzytEmZd7SaUdfuYpMZ
            84+23McAH8bcWZpCHfXzq7IstjYcwy9YZjXmJHklwCYmsS3g9JaMWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-26T18:09:22Z"
    mac: ENC[AES256_GCM,data:LqB1qcgAwuZcpfgIHsAi/oQFUUxCzg8iz+Yp9AannlkUkst3YK6ixT2U56f6qJMnZDvhllo6LGESxoueqgGW6fBjdfTdy0hA9vThGq5ZGp9tTy0ZuACFH4fRLLMC8prjTGQ+q3mOkxWUUL0+Z1Ze3whcSf1dC9JI1hFBjd9bbrE=,iv:UvKagd+LGkSvcb6mS/M9bxOmCD786OjiDnT/V1UeFDg=,tag:xoUg0ftzDMYr+pHYpMYl6Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
