---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blog-nginx
  namespace: self-hosted
spec:
  interval: 5m
  chart:
    spec:
      chart: nginx
      version: 9.7.4
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
  values:
    # image:
    #   registry: docker.io
    #   repository: bitnami/nginx
      # tag: 1.21.5-debian-10-r0
      # pullPolicy: IfNotPresent

    # podSecurityContext:
    #   enabled: true
    #   fsGroup: 1001
    #   sysctls: []

    # containerSecurityContext:
    #   enabled: true
    #   runAsUser: 1001
    #   runAsNonRoot: true

    # containerPorts:
    #   http: 8080
    #   https: "8443"

    cloneStaticSiteFromGit:
      enabled: true
      # image:
      #   registry: docker.io
      #   repository: bitnami/git
      #   # tag: 2.34.1-debian-10-r14
      #   pullPolicy: IfNotPresent
      #   pullSecrets: []
      repository: "https://github.com/alonso-m/blog.git"
      branch: "main"
      # interval: 60

    ingress:
      enabled: true
      # certManager: true
      hostname: ${SECRET_DOMAIN}
      # path: /
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        kubernetes.io/ingress.class: "traefik"
        hajimari.io/enable: "true"
        hajimari.io/icon: "application-outline"
        cert-manager.io/issue-temporary-certificate: "true"
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      tls: true

    metrics:
      enabled: true
      # image:
      #   registry: docker.io
      #   repository: bitnami/nginx-exporter
        # tag: 0.9.0-debian-10-r146
      #   pullPolicy: IfNotPresent
      #   pullSecrets: []
      # podAnnotations: {}
      # securityContext:
      #   enabled: true
      #   runAsUser: 1001
      # service:
      #   port: 9113
      #   annotations:
      #     prometheus.io/scrape: "true"
      #     prometheus.io/port: "{{ .Values.metrics.service.port }}"
      #   requests: {}
      # serviceMonitor:
      #   enabled: false
      #   namespace: "monitoring"
      #   interval: "10"
