---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blog-nginx
  namespace: self-hosted
spec:
  interval: 5m
  chart:
    spec:
      chart: nginx
      version: 10.0.1
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
  values:
    image:
      registry: docker.io
      repository: bitnami/nginx
      tag: 1.21.6-debian-10-r26

    cloneStaticSiteFromGit:
      enabled: true
      repository: "https://github.com/alonso-m/blog.git"
      branch: "main"

    service:
      type: ClusterIP
      externalTrafficPolicy: Local

    serverBlock: |-
      server {
        # listen 80;
        listen 8080 default_server;
        listen [::]:8080 default_server;
        server_name malonso.rf826.com;
        root /app/public;
        index index.html;

        location / {
               try_files $uri $uri/ =404;
        }
      }

    ingress:
      enabled: false

    metrics:
      enabled: false
