---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blog-nginx
  namespace: self-hosted
spec:
  interval: 5m
  chart:
    spec:
      chart: nginx
      version: 9.7.4
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
  values:
    cloneStaticSiteFromGit:
      enabled: true
      repository: "https://github.com/alonso-m/blog.git"
      branch: "main"

    # containerPorts:
    #   http: 80

    podSecurityContext:
      enabled: true
      fsGroup: 1001

    # containerSecurityContext:
    #   enabled: true
    #   runAsUser: 1001
    #   runAsNonRoot: true

    serverBlock: |-
      server {
        # listen ::8080 default_server;
        server_name rf826.com;
        location / {
          return 200 "hello!";
        }
      }

    ingress:
      enabled: true
      hostname: ${SECRET_DOMAIN}
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        kubernetes.io/ingress.class: "traefik"
        hajimari.io/enable: "true"
        hajimari.io/icon: "application-outline"
        cert-manager.io/issue-temporary-certificate: "true"
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      tls: true

    metrics:
      enabled: true
