# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: minio
    namespace: self-hosted
type: Opaque
stringData:
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:37iG3oDoPb8Vcvozgoo=,iv:q9KICHGL8Te58cJaoF1R/EtVUNmfXzCmXULA77GZM24=,tag:flqk9dCvwP2jqmGI7nk3lQ==,type:str]
    MINIO_ROOT_USER: ENC[AES256_GCM,data:0RuxazSrDw==,iv:R5pKCJNniqq7mk1s2lGZYAOG5ePBB8bzosMRRTB2VCo=,tag:8Bt0q2vpe/8f34M5eCnpvA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gpkhe6ap5xgmnrgjsc0vcxldp6g33gag3ul8ar2l5dvn32ccdunqpwdcuj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMeHR2YVNkTXBUYmk1Q3Fy
            cW5CV1UxMWR5RjRIYUNmNm1zQVhySWY4TmlVCnIvLzdiRnRDZDd4bXpxY255bzRF
            M2l6bGp1Y1JvaGZ5TnBDV050WjNMWkUKLS0tIGl0ZXRNdS9nOTh1OVJMV1hWVy9F
            SVdZSlhmaUwxdy91L0EvNnoyd0dYYzgKW2eC/tDhf+9u4VkvZRmW62XqNK6Bb0B+
            +n8uC49pjEHUuoxGXAyJYWACj+YLvITDqCRpWJldi6PSkvOPPMzR7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-06T18:50:25Z"
    mac: ENC[AES256_GCM,data:XWca8Jv3/itAX/2I+BiFnB6C/y09aAuRo87ypmxPK/ixu+Ippjp1n2srTHnYDKdladsVWzP1C5JBHLUAraXn0lAqTnpmA5UqqbGIP8A9W0BAjTcHRvM2F3DDrZlnjxhOzTIAPmIuLqZlQjfU2mzMDFPaceMEe0boDlZomuwZcMQ=,iv:vcap6RWJ6vT9+YqrWHI5LrGX51Asi77ss9CRB7RRouY=,tag:fbZVfeN16LGe6ZJVWR0zXQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
