---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost
  namespace: self-hosted
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: openebs-nvme-0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-mariadb
  namespace: self-hosted
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: openebs-nvme-0
