apiVersion: v1
kind: Secret
metadata:
    name: ghost-secret
    namespace: self-hosted
stringData:
    ghostPassword: ENC[AES256_GCM,data:ICZKLoqAousDXel6PAo=,iv:krUDUwvXvUytmonebPP8D82wCUNdoRKVHvXNZQlAfe8=,tag:RCqF5/dM/w4/l93KD/0BUQ==,type:str]
    ghostEmail: ENC[AES256_GCM,data:koHGE3rq5OXYcfbCknVw,iv:Xl8itxGiyOOvnwlUHa5+morE1m1zE4bZvPYO5pj7/tA=,tag:gQ6J2mXR4Aas9oiiFlufnA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-12-07T19:39:47Z"
    mac: ENC[AES256_GCM,data:2DNf6M8wzx55sDOLFxWAGCEN/vJxjczr/mo6anGtRjK7lQy+IgNGLc4Z+IM10q16L3mWfyQTQPuudsN/XbB0H4VuJoHnwhbRoF2gY3JczUY1KIzEhpJrYchxvYCF6BsE4QXeI99aSIXJ4oy6h+qMFy4w5PuIzHSKTe1JIJmd23A=,iv:U3EIPoE1Gy5UGdMHMFug/6bnVTHulz0ZEN8VesQXtD0=,tag:lXWElTeIXvM8oESpX23Qsw==,type:str]
    pgp:
        - created_at: "2021-12-07T19:39:47Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA452ft8CT80SARAAwBeuiDF8X1ouNecTsrxbnZ6OQxHvr0NqtIYMND9v2oF4
            8eWM25TBsmUISi2K9zeTt42mLawXM1CqEx9vNBMYh6qqg+uBJvNYDGW9mWhsYF6l
            10GmXAaRIjIEIZHo7cx71wekhuX9uvwodUi0YicHEOWRgDtf4h/NHG4SQys8I264
            xlpLl/HbcXQ/AwO5bTTJ7glJubIm+S3+SjCbY3LrN5Oj55fD67tBf2+3fYvP3gAC
            KCzetFaA0KUTHlW4Ud3QeZMdi4bMZi0rv+ak4UjXX92UnMU/5WQZuihUY8E4UVaL
            A2f7/LK1OZimKDsTQdecZCXPDRG0cAjG1177wOkMsRXC3e9PO4idrQDg7U+ZpRb0
            KK1T4kwXq2cAOf5iIByGEeNeLM65Di3FH2DceZrHdDV3Atz5C2SAAd91FDmNBFSp
            9sk/kpfAtiPYQDQ+jhuTJRehhs2BnZML51Q5CTHdOIhq/xG5BkTLy+LwqL87h6l4
            aby55r4xhHjx8J+oGN/N+UjFLuq2di20YBrsR+eD9ID31HKmRxqzbOCtrg3t1GT7
            VKZf5jcZulfhQYXBsmdevNTY9RGSLd8K6/xgWD1nuppwNWBIaCT0/GUUFenUSyfW
            E0h9RuuPuM3K8yMNVWAUzq0qqNtNweVzwLO+Pq7nksmI0uxwhkwbiUhc6ghFcsXS
            XAEb7MQl0cfdJfcJphwEArqhFGKzRd4CdpZQI8ubMSSv0Cue0S+MtsVbDd3jd21j
            TiXWN2uUo0pTpRHKQHUa75/2SwTH3Gwl3LN8719EzHrN8vvUqCzXbJytZ5ua
            =Qotm
            -----END PGP MESSAGE-----
          fp: A46BCBE5025D400A71759E6947630974DB001607
        - created_at: "2021-12-07T19:39:47Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAzKiqMukNpUtAQ/7BBBkjpTEoB6xcRvFknmuNkCaRGlNNGMlhhs4yaYCAD9u
            4eRaeYF01EuGMDe1OFV6U6gJYvV2VQWaSftUIK0vNFsqBAP3HzHGAyjjOuOJSYFz
            aBbmF4bsglrbf151QKXTV/hh/XyfLvndIs/vcK908H6czxK+Wqt9LHTI5m4neGY7
            iTO1/nNt/QLoaQ0T2nFl+6ckQQd1PdnURJDWknJj6bdP04YrLRpObY0caNUmsBiz
            CSNSOUUiBpUydlOZ9c8t6xIQomytKZwnu5sQmwzhfVJBc6XZrdVljAg6QBYFJZqn
            vCiQgroMa00ggED7cd8yjclR/o4r8Q74/kK7D3pA6cs/YRJAyOJiHqL0uuRVDSrE
            25lbo4acCEn0+mdBTbm02uiMuudJnxwMEUYNs/0D0abWmtOscW/PtNcPRn1n43+n
            qlR+eXAK3WwBX704BXJI9zLC35R/l58XHfR1eySMPMANxhBlLF/vRbkuFOu3H/Pl
            ypbF7cvXLuvrtvMkOwCZdPcR9JFwOHT1gBezBJTbcMQocvmbB2tQldNSa/kbX0ot
            /heQHUvfg4UEuBkibfQDT8nwZIQCpFTi8QI44kVAOyy6QJsoYd3dPmeBGQe65Q1L
            vZgziC93XNTrTHF8QuV3RXweQCFp0UMDXytfO0aZGZLIQMW17n/WulXuvbPD6SbS
            XAFuQh0Orf+WGr5Pcnh6MkGrPxDzQUXsZWvwXZNlJOZaT/KH1RUohkW2V8zjhJWu
            YVXfNYrOSL+Qwg/pI7aB8YUVJLn1D48k/fhcpIBwaoPa5yuG0ieMOxr84Kvv
            =Jw/V
            -----END PGP MESSAGE-----
          fp: 416E502A845A87487EF12661331A5023FC9B89BA
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
