apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: qbittorrent-vpnconfig
    namespace: downloads
stringData:
    vpnConfigfile: ENC[AES256_GCM,data:KZS2ufVbha5yjdTZ31HIpZyW5Ul5ioLX8268mrmQS5ZJm/PzVVdyyZ8clTwhv87mxB7KgFA8Ed33ul4sIAXTs0ZnI4A7mC9sVaIQRzohjvrumnsic2wDaVa/S50S3QOPYFxt9rDr3bMBRrKIy4QDE7yH4wa87wG82Fvf+9Feiwpbf5g6elibt3/upY/dNf5PfUaheggYLX7IJQSifetTPVLZNBRQ26i2oOFHYgFizS3jBvGtYoLhHl356Nx3OLwV31ErOmX8rswNVqe+qpjJD5/JQmHCWf+QmoCNVYND4FJKrjGopXdnpyIdK2O69ZmJLqIOlaoXWYfzTtsTyyOfdJKnP975QtboMMklvr/SkJRM69cZ0j/7Irj/ugdiOvLe,iv:vbCEIqi1g7MZHykfHqqnRKWI7CENgaQBNy7sCZ9X0gE=,tag:kYuw41Ww3SLK8181xaQa6Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-05T16:18:41Z"
    mac: ENC[AES256_GCM,data:QGwCJFR1L+ymnvJqfXqNvUUCDpy1BxiEpZHhQcXcYB0h92X227YMpb3Fh7lAfIwbr10esXEM7y+puUoAwCPEMNYJHwQ0zUuPqDI1kpMk7IIjSiOS0L5J9Btf23uYWTV94Jze38g4Bjw3LVdWF+OwH9cCpw77SC6sj5EM/+h0oQg=,iv:mvGZ/HV4j9PW/ov6hfKD+cOMytuC309i3VwjshqaCL0=,tag:YPo1sNdeCtgDYVjegp7dZw==,type:str]
    pgp:
        - created_at: "2021-04-13T09:41:19Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwAAAAAAAAAAARAAjnZKTe665twxJFj0UWAh5U9EnwuQxfJP6F3HX82g82g1
            Yx8P6VVoNxZAu72AJv0nutbpgxM8XbVaY21BTV1Ovk/oqHQ0XAHi9zpJAN1K9Lpb
            407ObbVF3hq7Sja/jPl4EjyBYFmWP26kb3zZYifJfTIBAAnTCcpfQP8a/TOsMDmL
            m+1jOpCDUjG0lqsCD4CpmZhlUesXLAiZHLfzP/qrB6nLwQyiPQEWHc7lIdtG/K9U
            SzmfV94KFw0EE2/O+q2dtMPpbu5dQFBycrQfh1nooScGoJVw1YLCIUHSQRDYtpDB
            8y4eB6/1fwmJmhDN2NXJA2HD/3ao1dqA5LQmpTImk1Qn4NK0EwVhmwp5/Ew2810P
            sMSvDZwTKTHfJCl73mLKYmDOewjJxXAengiyJa1Mwo9AbMIoaUJ8YoNv2CeXUQyi
            ydRFUP2uwM3AGsEjYAwGaIIYhlNl86Q1ThEFWLCxcbyA+gDp/utBBo6NOdhrpGAn
            hwJciSqMMV/ihAWn3nvnt3pZDQl8y7qmjthn6xrcf0hhXjrbKggvG1ZZrr0TOT86
            vyM1Bbis2CKZdrQ0MP9kwlImKsKLO2xfeVnvk+kqXybwsHGQ+MiShzHum+SgmcAc
            yGzeyzLUlnRTI5nM4ixP3xbuRVQDjjV+rZHsB6Pxon/0EanYkiQi8YsrJdMUkL7S
            XgFH2RhbzLKlW4Ir0xQp9RRP0eajmUdrWz2Kxvizfe+WaHfJMMpzRg36OxV2Ybx+
            anJIkKDGCs4659lt2d91KNgYK5FezoizGDK99Xispa7ObVpKJuwl6TpmOwB/TSg=
            =Qf5I
            -----END PGP MESSAGE-----
          fp: "0xBE954AA0B2A13EAD"
        - created_at: "2021-04-13T09:41:19Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwAAAAAAAAAAAQ//YcjB0YMtZPR7tUZ2wRJ+C23f8LcqSZNPT5FiaPV50eJr
            ebcQyc4C2b5ugbR9T3/8H2nbs+8Y1WltmHtK7jVhN903J8k0TV34cE3kUuhWK8ud
            FPt7pEvJH+PBWc8qzmw5vqR5SjBTQwxc6jfaq4F5v9iOJhKGff6f0AmSW3r5Prhh
            Fm4QIs8lR7n3IabACqs2gI5HmvCymagPoy5x+HwVKjh0ivzx/zCks90c+ho9Yij2
            062eziZIxwc1pZZiKtV0zOwcX2B21Tq46AG/R3BZ/2l9khgWf3LQ2FeNCdrNiF+3
            A6VPSbgR//naAEqKR3sPuxJ1ZFfjNf0aI6laOc+lHTrFpqGyPK/pJqR4/d2kWLQm
            YqAdaFLoC/6ByrnlBLwQgQvLxzNxFwoO5nnjWCysXT8HwWcoaJWHVF4kuDXeKJVE
            BdBXPtoqJSj3mCcA5EBjX0OSktt4RYYk/vApPls1VMkKyNglE+q18ZbzBNdHqYeD
            sleBXx4Bmx9UYCmXH1guMWtyhPpmZFygD3Qdf5q4DmNu/ES0Y2i8R/k67fAcfK70
            r1AygnWCK1VxS6alf1fh5/Ag1EMdXv6y2Z0eY3qWM7CIeRb3K7XR4fsPYE5TmPiJ
            j+T2+UFcIquioHmLc5dIbXjKySEDxbuq+q3F4/TvZ+O1voUouLinyG0ZdCYsz0rS
            XgH1kJXGmobIo6jX4DrWkzl6DzfyvjHTRwha7eQ22xfV6NcscQ80luli86PW1zek
            V/ix3GGisgoFUAAHerB7CzE/nu+vdrYETQ6+OUH85l81YWj+VfmcKeW8DNlxngM=
            =mMQJ
            -----END PGP MESSAGE-----
          fp: "0xEF97AF748D596FE2"
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.7.1
