---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: backups
spec:
  interval: 5m
  chart:
    spec:
      chart: velero
      version: 3.1.4
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/velero
      tag: v1.9.1

    configuration:
      extraEnvVars:
        TZ: "Europe/Amsterdam"

      provider: aws

      backupStorageLocation:
        name: default
        bucket: velero
        default: true
        config:
          region: us-east-1
          s3ForcePathStyle: true
          s3Url: http://minio.self-hosted:9000
          publicUrl: https://s3.${SECRET_DOMAIN}

      resticTimeout: 4h

    initContainers:
      - name: velero-plugin-for-aws
        image: ghcr.io/k8s-at-home/velero-plugin-for-aws:v1.5.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins

    credentials:
      existingSecret: minio

    schedules:
      daily-backup:
        schedule: "0 3 * * *"
        template:
          ttl: "168h"

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

    backupsEnabled: true

    snapshotsEnabled: false

    upgradeCRDs: false

    cleanUpCRDs: false

    kubectl:
      image:
        repository: ghcr.io/k8s-at-home/kubectl
        tag: v1.25.4

    deployRestic: true

    restic:
      podVolumePath: /var/lib/kubelet/pods
      privileged: true
      resources:
        requests:
          memory: 200Mi
          cpu: 15m
        limits:
          memory: 3000Mi

    resources:
      requests:
        memory: 300Mi
        cpu: 25m
      limits:
        memory: 1500Mi
