---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kured
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://weaveworks.github.io/kured
      chart: kured
      version: 2.10.1
      sourceRef:
        kind: HelmRepository
        name: weaveworks-kured-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: raspbernetes/kured
      tag: 1.8.0

    updateStrategy: RollingUpdate

    configuration:
      startTime: "0:00"
      endTime: "4:00"
      timeZone: "Europe/Amsterdam"

    tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"

    metrics:
      create: true

    extraArgs:
      notify-url: "${KURED_DISCORD_WEBHOOK}"
