---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kured
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://weaveworks.github.io/kured
      chart: kured
      version: 2.11.2
      sourceRef:
        kind: HelmRepository
        name: weaveworks-kured-charts
        namespace: flux-system
      interval: 5m

  valuesFrom:
    - kind: Secret
      name: kured
      valuesKey: discord-webhook
      targetPath: extraArgs.notify-url
      optional: false

  values:
    image:
      repository: raspbernetes/kured
      tag: 1.9.1

    updateStrategy: RollingUpdate

    configuration:
      startTime: "0:00"
      endTime: "4:00"
      timeZone: "Europe/Amsterdam"

    tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"

    metrics:
      create: true

    podAnnotations:
      secret.reloader.stakater.com/reload: "kured"
