apiVersion: v1
kind: Secret
metadata:
    name: kured
    namespace: kube-system
stringData:
    discord-webhook: ENC[AES256_GCM,data:eHkHquQqAiWSYzjWP4svmy4EwIVXrwXBxKMrPh72icl/h3jXsqTBUeAdN9NDwh6RXWlodCnEB6mRwtGU0EAAIf39EfXiymPh4ezHz3T/mERLrbxID28tk4NDwdI3pNnM8dZk2h1Pf72vls1qc4GOpUL44W47wNj4,iv:IKmztZ5opFLP1LFbttDn2StKupd+otBAosac0iCVt6s=,tag:XTerZOkN86aca5i0Ivyz+Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-12-06T10:41:32Z"
    mac: ENC[AES256_GCM,data:/YAy0S9oCZoBhfzBGxWQvg/8zAwj9jD5f4lqdAqMweus6oZLtUcimiGh5GYg9eifzMh5Pyw/2JMoXRJhY9QSVv1vZqE53ozV3qunL6/OlGbx04qXP+WFnXCHZQrz2DdCq5yVVpsbzXh6bGyRtZKJ0R5ip+8ecizH1Y0Z2EoiAII=,iv:bixVcWWnANElM4qqU5jC6dHqxBo4HugqDat6YUsEuoY=,tag:NWqkOkmASy4K5PxIBS5h5A==,type:str]
    pgp:
        - created_at: "2021-12-06T10:41:32Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA452ft8CT80SARAAqMAd6jznrUenF9Y0dOMGMACGpCkp6CwaTsIoo0E6g4Pl
            hBUcFeJ4D4m64r6br2cFBHVgqYSzm+pHq80o6wjDUgkvogkQ243/o4zayhVcSaad
            9EBypY7T9OjqgxodEOF7qdpNc2OarUYCP91gZ7LjqeOjXnRVVM8f0MxhULqgUCYb
            RioApO100PTHbpvbpPiq+h1AA5UMkrA9KD2K6mQgOMIYJvErMoZrDWVRs0o4b0GJ
            jzleFGabQ4ithiLfIZbce4nHUbiEn9YhKdMkbgKSpt3Wqh3b2bPJB2txJJh5xnGg
            0vA63uoynKUhfKvUUi+I+Z5SLa8MFLtsshdRFzcKYwLWDt7xO+oGjKTScoFjHVYW
            CebCkIwmOMjz6078O3RYeUQTIzbhSKlV4I5OtAdxA/hUHyraNLD0pUoHweJe1vo8
            35ZAZXY6+ESyDQKfUw64yZ4Bke+IdG2L7baUrg0BkAwYMa9wt0luRCqhI4QY+N8S
            ubrJW2mYz6k+kzeMSGFD5V36xlGnGL7D2/zqb8v73hT0LWKyiAxDHfpyjhoIYIm+
            CPdk2eoFMNHog/SmB9bRpT4K7f73jwSwD3+j+7mxLPhGWhO/rCHRObmzD3i96P3T
            7c18DkVmVLem1tUcKUfunNY2Nl/NjKClUxM6W0y/h1sM0a/kQSW5En8ClRytJQ7S
            XgENTQEjex21SpNMvmhs45hNgKzcLRet84eIVc2sglsMrOXP098Jfe5SZ1UnFOyG
            7eYJDdIxpWGwJhte1kxefaaWP93uIhEgElTe/S+yfDAmip7z0jjUGcYcN4SQvF8=
            =QcI9
            -----END PGP MESSAGE-----
          fp: A46BCBE5025D400A71759E6947630974DB001607
        - created_at: "2021-12-06T10:41:32Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAzKiqMukNpUtAQ//eLrc/ApfSK6Whi23DOV4f0gi9X3jEAPg0SUgr5oJQZ3E
            xrsBCOtlxKeLWFcrFJDAleak4lxIi1ToVYL6Lit2Gc2urTY1ARwhUYv0MJMe4rmI
            wccznZqe2B1jqzFaQfOYAghsRExp3UkFcF732t2bWo/ewCjtQQ1xn0jNnq9wekKz
            I5LB7J3CKScEHDOwRfq5HWSshhy5VN7t6tuE57PYwB+9VD71nW6gvgtASTPZvygN
            jgDpY7wGwSXUhXHKF/7L/LgjYHUm50Tup9j/XOdSoFHlaiD67u+8Z90L5d4l9d66
            lO9Y14leHGx6/CpVtAIJjmAptTgLNJR30vQSzgLzycplQp07LDipbjCrEl2yUTaR
            Kwq1H8GeyaRMs05fu/eEF/9G3w5OMKje0fssnhdZb9uhLt3PbJBD+3XjXvlZIgs6
            7s0Wclqi/CjQFFjOxO4bhZane/UMf0RlLmH/crLradfFNlumXg7qjcyxILR4kprj
            6I86tn40IqX3OfagZ33ztc1e5OoUyM25swdXzO8rdwz3Abirp0xEujSWGr6SGFho
            KVUbBIQAj845X200U3fjk61TsFmPcRkwCqwr7ZF8AV/Q25WkqkQDt/EcvzWfKeLp
            GVxSActpu8TGWGSrpMFFbCbQ92oyXYbyPwMp88pwhzXfuDtlEG6FHmXAfBNi+CLS
            XgEfltrEqy2OBuS0WoXmxF+TPqL1OnbK/cDOf5pOf5SPetqp2k0uZ6P00zD2pPJn
            e853lZwLXy1gdfaiVPxU6SybJwao/NhRe6HB+HFT+7odG8CkvReBUL2jqW2E6po=
            =a+yd
            -----END PGP MESSAGE-----
          fp: 416E502A845A87487EF12661331A5023FC9B89BA
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
