apiVersion: v1
kind: Secret
metadata:
    name: kured
    namespace: kube-system
stringData:
    discord-webhook: ENC[AES256_GCM,data:GRKaL/x3njRFKxZCPdOdlygdFUIzZJN93vErAUa4n0ES4Iff91CCPj6mPImYtOaj4lCR0DH06IJh8Q3exYsMvnDTKj1Yl8b7e1K+1LHnEn9Ryn42ei5Oq5t5ivxC0qlyMOSLJeV5O1gk8VP/9uBIGXeHweYp6Oz+,iv:LETX1DMS3Fe9K5vGDvGoL8iVXECdP+z2l7nga1/NL4Y=,tag:bQm3dpZmu9BVtLvE4djtJQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-12-04T07:19:51Z"
    mac: ENC[AES256_GCM,data:3R7pSg7Sgmhud3F4RbmUr1VFGJrjOZQaYSyhJwebS5Z2qzRzlgDgSczAoxDBaFbcoL3NEm6xm294esjfxpdHtd1ir8z49+gqovWWBZjNC7LDo63+NIoSbTSB0Y7LVGpve5W20M+0kyU4YYetF19HKfj9+3GrRumHFQ2JFKWgLVw=,iv:TUFmKpYE0V06yVZKajNkHTZxccK4UShHQaYCFfPyb2g=,tag:E5r1I1wOWKC1v8PPFVhcDw==,type:str]
    pgp:
        - created_at: "2021-12-04T07:19:51Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA452ft8CT80SAQ/9EsEdRNla8G7RmYyx4TfDAHttR+sikU+lrtL0IkrxtIIk
            UmdoT9C0xyFUGokkqx7Dv2Qxs83xbv/UTkqQF8KQKAgEKcPuUxculQXMPuJgaqAi
            K3KKSIgUg+JIwv+VVpysumkgOj+Nsi/arU70wBa5bCg1AcmsCTEdkizLopCt4rqz
            +3594dzd4p0YG3g4yznl1l5fHwxey9EJeqYsLeCDPFxLRW562Nkls/9ksYi8+EDN
            nHbTHvvTc8WxuSdUKDcKL2KaFCFNeCQW1tWvn7RMy3CTMEsTzGrL79skWyIbbyjS
            n5AkXPKDL0h4vY/IzkwI+CmAN4CBq4sYgpubR4zsMgRz/Ou0KRvpWSvVRsxC6We7
            zeE1OIgWD3TeXKJIIjUhzaErgOESQArHWxZ5AWmyBuRYKAUsEot51OePgfdE1h9Z
            aUGlEicQqk/5sxR4TPi7WO4WltHOge2coEdTf8TS3wyCdojTERpBrBskzHMUOjED
            snXCWCSqHQANVBApVFUpGGfCWdEnh22CG3tjUYoRNzQdpf1KQGlR5DMva4jctYM5
            RkHr6bwhxsHFEUiblkglCJNJO3ZvqtcuMzKU9hal+xPM37X7GLj4SboW5Qkzhsya
            nad/NVEbYOHWZTwy7wKfjBRY6f2mbX2PcOyinUYPrdeqMcHRRJGEp8+1ABdg63jS
            XgGBNVZte5qAMOqPaf/QMMB3KcGsFlSokmIL7yCvHYz0LboQl8V7zyFrA1kYp9sa
            SYwETq3MhhZrwGwsbCcWdBOlBdh0uAdMH63FHJoyg6HA5U+ChTwyfRTSYHx5gs4=
            =wCvH
            -----END PGP MESSAGE-----
          fp: A46BCBE5025D400A71759E6947630974DB001607
        - created_at: "2021-12-04T07:19:51Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAzKiqMukNpUtAQ//fDr7xoAh7FFkIXdwcSmIEmIH64DqGmukbywGZ6mRWFmF
            IKsQKYsZRu0EOpp1Td16SvyKb4xJDoNeOk05o5pFgIBFrH02W1uD5mVOym3mLSua
            lxkKvZLScMWNq2oZmoBjATtVHW7bK0pa3UYHJpR6BMIJXrANcTFJ4Uad+W9BhFvO
            m2Pj6NruF2FAiOKNBa2UKTc4ZEp5qXCwzNDwgwobF6gyIToSB9EGkfWm0rOL8Z3/
            eyQ88ymE4vxOCqCEMQsNIf7xv/Vo2viicfeYl+OG70zXANKD2cVUTwvUjyeQ0arR
            gR5pQNmvZQ9+F2V+Td+CHJpmrLczJL5lMAaxKOOVrn+/usV5Fh/Bzn3QOyKijJpk
            zqA04KRwVy6d79kGKGPf0IJjNrNLApy0SNsyluPi0hHoU7FYLuLl/KE7QmtIFQhm
            mdQjc+KoOMPDEOrRgAaBQjJYktXnTadsgIhJCJjpvtaKr40I0F6F9Bu21BVbEw3D
            z68hNx+nGVtQ1NIxpqs8o5pCGUe7TYkkpvBBwe0XikLuyRxKF+bV2kvw1HeXvyfK
            2rYlX2RNUCvegpzTe0qsJGwNOquNCGoe3/n6th7THEzFzpDkQDPdT+y9IbfBnPlS
            7kEhcDitoyRH/d6ancvz4c70etNGUZEn9JqWB9pwcgSKw8Da9vQ6m6gz5gTvY1HS
            XgGJvLSDhee7agw63o3SQx4++tjJssRR+ujwc8BfnmOLxc9aBIy7HlOm/rA886CZ
            Ur62qfEgi2W6ZNRtlHvG9LjNCw1e5YEcm8Hgk0E3aiijJ5G8C2nGR+lj9br2yRo=
            =PTrt
            -----END PGP MESSAGE-----
          fp: 416E502A845A87487EF12661331A5023FC9B89BA
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
