kind: Secret
ansible_user: ENC[AES256_GCM,data:0/KeHOyp,iv:sjxUFcZ1cGNr7acm0BmU9z7OCiX9mURtXypo/JboO9w=,tag:BJVVYaO9yJWiEc63VRai0A==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:WfA2Vi3PyCoh,iv:ytimoLJqGo4JUQvewW0tKU5Kqd4NQ17B4gPyl+pjC1A=,tag:0BNZ6yfQXI69wnCgstpZiw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-19T14:23:21Z"
    mac: ENC[AES256_GCM,data:O6E58cnIvDc0qNYu0gshe159ikKrAsthIjrmriDAs76ulhbX5YqYiAF/GFj8GaRgzeQXm0PZb3dEYStJOdxlW9ya24WqZvhzhnbvhZcyE9LYHn2oVPyBldOqrDgHm7oGaz1cvxp7mY5FUs++JzUzI/U0mp5uy6NyCmrNVULKvhs=,iv:iexRoHa5riIViFerXgPpwpFT8MzmGLPVDPJs5veXR/c=,tag:a1OgyEQ5ggoy0R9VBAXdrQ==,type:str]
    pgp:
        - created_at: "2021-11-19T14:23:21Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAzKiqMukNpUtARAAzamWPkbDNfS8hleqr1dkMCiMD4c0kFCzf/UxuYnCs5O4
            LUo7JVfTtZMNoIiyhD73H62H9EzlTeFr5O22qoVfbUzoCDYQUkDDiuaBzAvsAAhh
            p+DgJNsZZtcQW5r/Z8TIOw1DNxiK78smHFRFAt0sY15eV19FldYM+A0/eaUd5EDE
            5k3Rf2kSkiWxIoxeC8e2q+bo+jeNwGUQ50PqbpNCmwrRx+S4PAt+I6znVApJSbje
            PBuyR0iujuazVBRZLBKN171SrjTDC+yzeDMPRbJhK1Z4GFIUHxr8Ldg5AD2vTfVq
            9ISr3Rkfv1BirHkr4qJRmx9O+NA/IFoK7+PrevQY0Ts4j/JzF78AQuamuIkmZDbM
            zd6P2S9Fki64ugJ1ss6mc9Zh71+0olXORJKoROw+DC07O+HFDEcsrustUgnIw6JK
            qI2DI8tniWTDLORFcTRVwACPAn8/brlFgQU2TDY5y4ChNLBDDSu9ymACvd3MCKsJ
            DBYnmQBd648PUfuyU/Hi5e2P4b99Rjd2rTxbYq4/rvub6emvPaXpysuSQjDbv/iR
            6s0cdXhKtw1+QbzQswklAIvsvn7vz7FOw5RV5egCTkD85XTiOCPzIP9PfLKecncc
            fhuAwAbbzNymE2t4NsLLGJGB1gyhDrD43oiFU7o5rSugPoAtUhN5cZM/LvMJ5zLS
            XgHcYRNMCWULEbUVorxrd/fehfNBnsXdJgjkvcNtEuzX5eAs0JcBU8TmGUollnAX
            +a/rUL7kbOxq4Q/YZV/aU3rTml8QAkof6wNy/vAyS+EvJEIkhjzuR15PTge8ess=
            =vQ8Q
            -----END PGP MESSAGE-----
          fp: 416E502A845A87487EF12661331A5023FC9B89BA
    unencrypted_regex: ^(kind)$
    version: 3.7.1
