---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE: 192.168.188.230-192.168.188.239
  METALLB_TRAEFIK_ADDR: 192.168.188.230
  SVC_PIHOLE_ADDR: 192.168.188.231
