# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: null
    SECRET_CLOUDFLARE_EMAIL: null
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-19T14:23:20Z"
    mac: ENC[AES256_GCM,data:BL1YBtO/syxOxjQ8OgeYUDebD44AG59ZmoArXndpw66OsUQ96TAObLm6hNWFWCADdV39n7qp0rl0BnOWzjdfTTnVvtARURXpcJPeIxiQMJVQec6F4AxR928/YaZ/XYVnoJQ5KHxt4kmWH03hvJk7F0TmK5FD8IZv1+6Yxyc18oY=,iv:nYA84+BExis7IBPDxrxV2nghNz1ZTsm3Ja5BmoCQNxw=,tag:HtyFGCmKB8B/qN2zNS1RtQ==,type:str]
    pgp:
        - created_at: "2021-11-19T14:23:20Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA452ft8CT80SAQ/9Fg+MTk1syLrSqIXTAAPDNvbSJeYJ8ckPnx1rtEHu4SXv
            hsjk6tay5iRABMggtU6jeMOWF64weKXmlYdRS+jODDtw4wa1IK5IKsFDbB5at/w2
            HyYBlBV7f/7Nia6/+jmABA5LXLdcSZSxn3u5I2u0oEuyCKOFNGrEcJbpH0UfKKTp
            5tjMqZ5ohGuYo3nESz6San6X031+y9X3lzQuqrke/LxCKE3N/78QuDHEYCG2Ic1D
            /Me+AJi1zDYsIMAf6pHC0PbVfwJeEbNlGt9VyjtSwv6F3fUSxkeKF6FGJPizvNpF
            rO1vN7O9j90BCrR5qP8EQfzuHSdj9P6p7CHEbR4NUI/7pT8K54Wzc2xoLo5PdwLU
            P+9pTxgnVbaD2v+kST14FN3KOSaNBQD0G7k1ZEsxP6G9plVflXqMywHApvCMz+Nz
            qzyMlx76tRJu4oA7yv/PTk0eNUufXK8xUWWch8x0lQcF503ZNys11P/2q+XbAG7k
            WxObFTqhwsaY9Hgx6u5pKFo3yx1g04avgxStPFcmlH69R/rKW3lq0MlRHR8WaNtD
            P/77ONkPnRFdpQwIsYus244juSTCfRZjo4X0r9Mj8vazZzgOo6ZgI8/bVLvmm+pG
            LvBhk32CNiqVJw27Ug0itK+dFP0xVuCkULiXWceHk5CgZkiqb6eXUwTpxcQFqBLS
            XgEZFCsPT+xMQBK6rpITOpGnqBMMz+9UJ5CRYDXheBzaUFL79txKDpTNYJjxqhT0
            tNY29VsdmEmSejccU/ogGVPUjhjQn1nCEHW7FEQ+cmb/nHd4BodsKp0Ku8kpYrk=
            =uc2n
            -----END PGP MESSAGE-----
          fp: A46BCBE5025D400A71759E6947630974DB001607
        - created_at: "2021-11-19T14:23:20Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAzKiqMukNpUtARAAl5YvFN96Ji3TMIjaK5o1XRbU9kv721NSnfvDq9em9Xje
            ygmLzN3D1rJj3llOoPl3qknCOLJHh84jRjMG2n+gPrU2NN1Fu3cpRJkBzKRbiqdD
            cq41H7maTFaC1JvFv19Kxwyh0tZeHuHlFT+FBcOP6d4N5BiPxufiqOG3WHvbxenW
            mPSozlQWBTJG9NMwRn60mWPRtMVCGLNQSr4CAdL2OqGZGs36v/V+CduKjzjOCk6O
            gxmi9lohi+7nyduJkh8lyCLlrZ6pDnlH1mOxnV1IcWTDujqCFKt6NCJ2uwwBU4jd
            a7qAHtozAaUP1Hr1YeYIPxR7OVgcB5o/873v4bYeXDImNRvX6um46uu+aaJHNNSj
            nu9Hjt5lcPuzVJhqveBn6uPJ1AFfafBy0OgsHw1h+rjMejNcHkY3IpZ87UGjjRRO
            hIL5CheEG5xGKwCx75EaQv5xLmVVdcz4kK+TLfzIZ/cPDwL765jxe8G2IkLwzjjY
            +OaWZgzThlAntQmG5ZmQGgAE+jFF3UzmxG2lc1ZVVviLYIFvZT2pJQLg4BNqgLBm
            bxyhhtcfbTiYujl/BeVgWC7yqWKoT2eqT47BCO7Zc3as8JagrJBnnMyd+BP68sFE
            IVozTDQYYZ9BZPUPg78gV7APPmCXM/YV09hcZ5/a0hMM07OJN5q+38QhM7e1AQbS
            XgHd/4YMvTYQJEf3rbgugDx9RabG2EaEwTB905Ga7/Fd9J5SAxvS8LpcMswa3MK0
            bPdqtQWu6qiMcsB9kOVBhaaCx9TYOo6+FkA+gbd9NnquEIt+ouxVLHvsAAdhgFE=
            =V20Y
            -----END PGP MESSAGE-----
          fp: 416E502A845A87487EF12661331A5023FC9B89BA
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
