# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:X7INEZYIxj9oIQ==,iv:ox0Wps9EN7lC650Zl1QWAYTsNps0KL1AYqE/pAw6cCs=,tag:3P4D094FyTpauU3yopRqeg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:H4GN/rn7sn1V3hqa48eozAavbVusMqA=,iv:4KzE7lYXj6YXxVm80MRFoXx2vpudr6LrkD53vd7AaCE=,tag:vJIYAwEMmgYPf7k2GIjQFg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-22T15:16:21Z"
    mac: ENC[AES256_GCM,data:66V6JwwORV5UR6XiH1xbLYchjJY9gg2sfblYAZZ1/l5d4OjkzJmYVQA/6SgDvfg6pY5pVTgG6tMCNpHGBUEeG6K6MagQmMER+bPzabWLVeFyOdjjXtWLZB+QsLgWRyDJITQXUaNA/WjzN+EfUhNsIwK+I3JlcqHp2w2qUGuENyM=,iv:PRjMwXPbxEE+WvDKFSfFLpxweCM4SY7PB9EWU4CcGiE=,tag:w+TLqq391qFsbFiZEMq+iw==,type:str]
    pgp:
        - created_at: "2021-10-22T15:16:21Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA452ft8CT80SARAAzPwJQsBGf4ygXYfxeKCgmAZbVriPWBxyE+BAzg0nimgt
            fw7ypHDfxzDExTolHw9Niz2p+5i8NEmQRrY0tCCQ+UZfO1yPJPv14lW+Gmtrrw1n
            iLsWXTWieBK1IRO1P2++P+nzhUBYXyRU7exsy0kUux77skUZpIvGfmsHKpsVPjqR
            VeCiAtxZ537JMjNIdc4mZ943OQDLGipBpeIrcITZPvaf5hn6fFE2cd8hMZuyz8JC
            ZC/kGPvt+D1VZJ5G6UeQZm37EIB/YnK8lYv626i21wi2xiz1sdrwXA3VXkp3zb1a
            hEf+BrqPXnUzuzL01NOMUVavXrp5w+jaodi7XktymD5yXc+U3DjnjhrDxDqhw2vq
            iVeFfbs1sxfzl5XCSih8x8VOXLxez9wTKezSwaPewVidSe2rZqno+6iZAQH4ODNG
            D/kB6GtVdVjvuKZjfLf2M1gNwKJQjqCRLmXvNCi0jTrNiG9xZ/7GZRK8MtG+Pyp7
            PGcVCY2lR6s2BWSapjeu94TjvjItq/FkBUsyafC9pMZGiqhbPhQE47G/sy/lZAsd
            idUPl3kFYjUyzpP3CUGveuH134FC2iBrQjhEeq9N5+cbQI1asQZkRYOpaQwfIm0u
            RT/h/hsxTIaonKQandgFBxWJ+IJvp/O2pIufUJXoVfW4t2KoI/TeibfjASmCf1fS
            XAEAfg/93gFW25BgnIovicEdX+0FWGXkqmNs4Lm10tXN6WKwQO6hBN86b7/JXF9r
            hIZDCfUJfERRq1wPrJ+caS1HDZCTxeI9qsV0070/Lj1yb0i/C+FMkbp/JknZ
            =zYNm
            -----END PGP MESSAGE-----
          fp: A46BCBE5025D400A71759E6947630974DB001607
        - created_at: "2021-10-22T15:16:21Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAzKiqMukNpUtAQ//Y7fu1vz2FSarkuJQxNoSfTB57FM1NLWPhGt04rpACLor
            PX8VbiaBISqWCTf8CMU0gpPHRDK+qwF0/t2F56fpZ8nxDLpsVARwgJ4s69zG6820
            J0uycQChGg9EYDYefVGAoJSC62vJjhR9QsvzPlWf4h8bRkcRnGc09tgHApSaXXOI
            elg4TdE9W7NtTV40UridkSXYcoSpTgdiHtmNZgpZIfHNDeAsqWEvaDgd6AI/YmVs
            O+tNMxffKo3/qNdvmYwOvdY8XWXXOpHUeUoDEG2LGcTMSilMdceLLFpRvveeZnCC
            X3dxEjI5uHfJedukANqhn7ubonOmcRgwj4+QENE35ht4pAqz5247GttL3/hEl6IJ
            hyxo4cfMZchbxUhY+1+RGDVq7KM4fyIYplwngZc0HCoLYvzUr97OYlPbkfuclmRy
            eKgE3/wEKWlyE2Wgmvvw3L1F4fV6geyx+ZmvjO5+npIVkCAJBUuF+rAXRptz9WyM
            l05sVrxSNef9N8vhG4oI/5x5SvsP+pfQdK/JclNT2UiF2QIAfeL9+hlf8p8QoMw+
            FH4FOU9NhK+ysr3nkZP9GmaQtXRT82vLYcfPpoOb4cvi0x2qDBgga3GGpqrxi8wm
            LaiBd1F0mxbTu5nF2MavPvoaXeiPmPque951HG6iDQSXtBeUts3ul23lWKJjOhfS
            XAFLXyQ59S8TXtw8p3YrYBKiRAMlYnpOLkI+nC4jdVV1cba3XRw9xtb4yVzsUE3k
            29B9chZYM3I46zeMttJv+HiYV3dHo6NraaRzyU/uSOq1BZZYpfp42o6pjmSX
            =1IP4
            -----END PGP MESSAGE-----
          fp: 416E502A845A87487EF12661331A5023FC9B89BA
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
