apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden
    namespace: self-hosted
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:GUEtFY+eF8SE6I8VMcBsOPHlNPmAUgJwRUNueyyAn0RrXGAeNajS8vS4B7BJIfgPnZXxsePo4LqlR4xm9BjLcg==,iv:7VOh7ka2FQbE5xaP/Fvmve4O0FQPE9TX1/MZ9EdxoFo=,tag:H7NBzSLGlSSQ1BOcMwcwLw==,type:str]
    SMTP_FROM: ENC[AES256_GCM,data:LuhZbTiyMYj8vJRUI0b5eQlfv+U=,iv:P66x1sDDNU4wEAJcfNswxYeXAvtaThRTYyb7vX3k9UE=,tag:bLClQByXCbwenUZ4x49ZMw==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:DaAw4Q31N3nn6JJgZplpCQ==,iv:OLnf7fIgsp3RAFJk0dV1koTTIsZrK6uS4qf9TUP9puM=,tag:KEgfYtW41n8E/o5ekZlbOw==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:tQNBRXaZwthIYjXcpLULmpchM60o4WU=,iv:xcXnB0PH9abEs3Hv9UvZRW/YMyfzrC2mK5tIzbd6dJ8=,tag:ZYAXN9ThLHROXyr6hl6L4g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-26T19:35:23Z"
    mac: ENC[AES256_GCM,data:fm4vehgoTsOSAu7hDhM1p6K7gCRhFsvZ9rU9Tqb3NVJCYXtjTIpBhvusQ7Lv7xM5Cvdqr0g8mKt0UTJGC8q1wuPKlNbPvsFZ3MLom22IInSc0G/p239zNQdkPRe+ap4Cuc1zvlu552UIJraKnINb0OIb4g1w4vgN6ufzxLnzNz0=,iv:RsjSzSQ3aUPSWPmG4BA7YGea91K+cVe6ppHPX4XmI9A=,tag:E1mNtVrq4V63+Q8snZh76g==,type:str]
    pgp:
        - created_at: "2021-10-26T19:35:23Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA452ft8CT80SARAAhE/PZFWTuBkWHYv+c4EXVCIxrJN66qz/AX0DLkIOzpdC
            9frHAHKtw2dqT2SsexoGyrjWP9Czapx0x3oPRDligdotfYRJFQ9QuoM9TFsAUvRd
            Afq/OGMKDiRvKM3LOrC09dGTBT4e7g3GeIwVYlYRMPZWPKRX5y9k1agj8K0TtLQ9
            qrgco7XPpFrJb3o7Ui+JWvEWxYQKZ5XXwgW8luNYK+RqkFO3ZiWWcBGcqvywpyms
            K8zSdjRqpfiPMO44wBkdtdXp2KvM/Bzbn9aaSPHMvsMflYdxOvWtlNa9AK2jKL30
            qN6HZmpfKmiTef68RqI1W/O/roSmhvzT51BXZlSietPk9RAfxVwe3e6uBKULygvT
            a0q82MpTB6PkWzl0rIfufU3YIAo5kT874RAjPmoC3+a2u7PTAPg0BDr+/HRRifla
            ZMinVVMF6Y2wB9P/PDOW1BvNK73xisqfi+ITrAMrcL4aQEXs2j3EEX+Wa9yZ84FT
            5B1Yf0I//Mvwvy6DnnSPOerOqXT4jdiLzFFFW3SOeSje68eX8m2jyl1+28qyQK6v
            exylznHcc5M8Iz10C6MWT9bnsTJ6n5XlzJFDwgOoheCmo4WD7DYAEZ9t8mf/DXe/
            2oAHXPAZTITD5RH6hirslK2nCVqemZOUantKTyQPxnb+p0BbLvcKFBJe6AS7BjXS
            XAFZ1deuVxBjb2Xy2rsQdS7kaH5Euizc9Rt7Z/FA1kgTU7xZXkK/hv/DztKKQ89P
            FNt1uyvsoViLMa+0cPYYjklworHwvBF8808GkNS0Dv+uT6JusvfrYoEin8sC
            =dDWV
            -----END PGP MESSAGE-----
          fp: A46BCBE5025D400A71759E6947630974DB001607
        - created_at: "2021-10-26T19:35:23Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAzKiqMukNpUtAQ//U454gTC28FVJdZygqSLId0BWNheqOf6jeC1LzKyAEAox
            WmmFxPin+UMz1L9+gHzylivO4YYoqhkT7xRyCrZF66CSxO9IL0QrLAdHLE+Ox4Nm
            s935WbhEyNxsK/9ollrW4qs91FbDXen70rVNB+grrlj/SJS301lqk9iUgK/tdgPp
            FAzRtexUGbHlyAg4gOnVbMzGq+Lxzfub7BGFOU0F4uJmHII0L2Jdvu0/rTPbJuoN
            9oRcK0hG70pz2zD48FckwyS6CfWItwc8T2C+KkHGHigu55+V1Y1E5fl+2uspOBiK
            JiKhrzNy7bo9DK7Y3dr9sJZaqCu6YV4gioyZUQR/mAJ4IN05CELD9X4+xxEOkeGt
            lAT9WmrvxodA5C1VJPT+JjOAF8kytQV33UxM8gP82aA9EM0rYhWlDfxvNOZfgkud
            VHPUbNLW71L/QmmriFnm2l+uwPIGrQ1GCOHT3fPHmu9Z0i2SfNzoXNBESnT3gyWi
            a+jVpRWW+bgT19tMrZcNqTA8chTLxtN/zaI4QAWVZ8BJu1v8SG/9fL18VS+C9BSx
            b0YeSNnejxJ99pH74dYfTFJsBzCYdmyvAX7jPFTMqHOpp7FyiMlHdese+E44W+xJ
            u+Ukf8NBX58V8Y3/vq3A2lrFTE8+WeycAPJd2QD3xfBuH5j1CBkB7+16Hs9oeq7S
            XAEH8NDLm+NMdaCrkOscSuoki2UYjGMmncVNsL4IHxv6oB/D8W1QmwkV0qSSgbu+
            fDfibqMEPNxxk5UP5Q9/QL9zIC31TouxtGCnHOnmNleVdOpXm15Lh2g/5SK2
            =n/aG
            -----END PGP MESSAGE-----
          fp: 416E502A845A87487EF12661331A5023FC9B89BA
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
