---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: syncthing
  namespace: self-hosted
spec:
  interval: 5m
  chart:
    spec:
      chart: syncthing
      version: 3.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: syncthing/syncthing
      tag: 1.18.6

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          cert-manager.io/issue-temporary-certificate: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "folder-sync"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: syncthing.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - syncthing.${SECRET_DOMAIN}
            secretName: "syncthing-tls"

    service:
      port:
        port: 8384
      additionalServices:
        - enabled: true
          nameSuffix: listen
          type: ClusterIP
        # port:
        #   port: 22000
        #   name: listen
        #   protocol: TCP
        #   targetPort: 22000
        # externalTrafficPolicy: Local
        - enabled: true
          nameSuffix: discovery
          type: ClusterIP
        # port:
        #   port: 21027
        #   name: discovery
        #   protocol: UDP
        #   targetPort: 21027
        # externalTrafficPolicy: Local

    persistence:
      config:
        enabled: true
        existingClaim: syncthing
        mountPath: /var/syncthing

    resources:
      requests:
        cpu: 11m
        memory: 204M

    podAnnotations:
      backup.velero.io/backup-volumes: config
