---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing
  namespace: self-hosted
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
  storageClassName: openebs-nvme-0
