---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: echo-server
  namespace: self-hosted
spec:
  interval: 5m
  chart:
    spec:
      chart: echo-server
      version: 0.5.0
      sourceRef:
        kind: HelmRepository
        name: ealenn-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ealen/echo-server
      tag: 0.7.0

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: letsencrypt-production
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.middlewares: "networking-rfc1918@kubernetescrd"
      hosts:
        - host: echo-server.${SECRET_DOMAIN}
          paths:
            - "/"
      tls:
        - secretName: tls.echo-server
          hosts:
            - echo-server.${SECRET_DOMAIN}

    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 96Mi
