---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: filebrowser
  namespace: downloads
spec:
  interval: 5m
  chart:
    spec:
      chart: /charts/kah-common/
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: filebrowser/filebrowser
      tag: v2.20.1

    nameOverride: filebrowser

    env:
      FB_DATABASE: "/config/filebrowser.db"
      FB_ROOT: "/media"
      FB_LOG: "stdout"
      TZ: "Europe/Amsterdam"

    envFrom:
      - secretRef:
          name: filebrowser

    service:
      main:
        ports:
          http:
            port: 80

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "folder"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          cert-manager.io/issue-temporary-certificate: "true"
          kubernetes.io/tls-acme: "true"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "filebrowser.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "filebrowser.${SECRET_DOMAIN}"
            secretName: "filebrowser-tls"

    persistence:
      media:
        enabled: true
        existingClaim: downloads

    podAnnotations:
      secret.reloader.stakater.com/reload: "filebrowser"

    resources:
      requests:
        memory: 100M
        cpu: 100m
      limits:
        memory: 2000M
