---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser
  namespace: downloads
  labels:
#    kasten.io/backup-volume: "enabled"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: openebs-nvme-0
