apiVersion: v1
kind: Secret
metadata:
    name: minio
    namespace: self-hosted
type: Opaque
stringData:
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:IC+cr6WCZlIViN/uUX0=,iv:0rn9scg1vKMbEnUNUCs/3Pf1PeXEDce5IOMn8jSahg4=,tag:EZQTG77W03KLrdKGGmh0Nw==,type:str]
    MINIO_ROOT_USER: ENC[AES256_GCM,data:w+0SUSK/7w==,iv:QfYrJTG4id5wdjKMpW2V1A7Gbs/9ikZoIKwO93b54mw=,tag:xPCB/Xq4bcxSpTiTii+kWA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gpkhe6ap5xgmnrgjsc0vcxldp6g33gag3ul8ar2l5dvn32ccdunqpwdcuj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTUJUZGFBcGVGTUFodzVz
            djZEQzIwSGhyd0FUN1JneWJHbkQrb0xnVm5NCjk2Tlk3SkYwM2dxUWYvL0tqdmg0
            RGU1VGRtTThJN0JxZTY0bEdsK0lsZTgKLS0tIG5sSXpSL3RmbEE2Qm1tZCtzc09m
            WkxSeG5oQW5namVvdC9PakZKZ1I0U2MKa/V0CKIyGcms/6feIHRcTpLO4K7xiY/G
            DamZe2D7r0p+5Xdl6Z8luSxut/UnTJ0P53t3+EiYxU2sqBOvtzA6nQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-06T18:50:25Z"
    mac: ENC[AES256_GCM,data:XHS+zbp36jO06HM8/6hoBxoYCkX7nAZH6zk4MTgJxzGRsV16DAMr9M4KvlrCHE29oKPwU6QFkhMRbtaVIw+AmCSb5snV9iucQx9MzFMTcJ0ZpsjfXWysG2tb8OuefZSIyvaaaRTqpiNn1FGDqkY5m28TduzMLhmPzRouB9Msp3w=,iv:5dsCv1xwYMeRzrkmbI12mKB55ndkD61lwOXQBDaGH8k=,tag:YvFTe+tlkH7o7oH8pGJEbw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
