---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hajimari
  namespace: self-hosted
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-nvme-0
  resources:
    requests:
      storage: 128Mi
