---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: transmission
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://utkuozdemir.org/helm-charts
      chart: transmission-openvpn
      version: 1.0.11
      sourceRef:
        kind: HelmRepository
        name: utkuozdemir-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: haugene/transmission-openvpn
      tag: latest
    env:
      OPENVPN_PROVIDER: "NORDVPN" # VPN provider. List of supported providers: https://haugene.github.io/docker-transmission-openvpn/supported-providers/
      NORDVPN_PROTOCOL: "TCP"
      NORDVPN_COUNTRY: "NL" # Country where we want to download over VPN
      NORDVPN_CATEGORY: "P2P" # VPN Type
      LOCAL_NETWORK: "192.168.188.0/24"
      TRANSMISSION_PEER_PORT: "47444"
      TRANSMISSION_DOWNLOAD_DIR: "/downloads/transmission"
      TRANSMISSION_RPC_AUTHENTICATION_REQUIRED: "true"
      TRANSMISSION_DOWNLOAD_QUEUE_SIZE: "8"
      PUID: "1000"
      PGID: "1000"
      OPENVPN_USERNAME: "${OPENVPN_USERNAME}"
      OPENVPN_PASSWORD: "${OPENVPN_PASSWORD}"
      TRANSMISSION_RPC_USERNAME: "${TRANSMISSION_RPC_USERNAME}"
      TRANSMISSION_RPC_PASSWORD: "${TRANSMISSION_RPC_PASSWORD}"

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
#          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
#          external-dns/is-public: "true"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          cert-manager.io/issue-temporary-certificate: "true"
#            hajimari.io/enable: "true"
#            hajimari.io/icon: "shield-key"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: download.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - download.${SECRET_DOMAIN}
            secretName: "download-tls"
    persistence:
      data:
        enabled: true
        existingClaim: "filebrowser-media-v1"
