---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: transmission
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://utkuozdemir.org/helm-charts
      chart: transmission-openvpn
      version: 1.10.11
      sourceRef:
        kind: HelmRepository
        name: utkuozdemir-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: haugene/transmission-openvpn
      tag: latest
    env:
      - name: OPENVPN_PROVIDER
        value: "NORDVPN" # VPN provider. List of supported providers: https://haugene.github.io/docker-transmission-openvpn/supported-providers/
      - name: NORDVPN_PROTOCOL
        value: "TCP"
      - name: NORDVPN_COUNTRY
        value: "NL" # Country where we want to download over VPN
      - name: NORDVPN_CATEGORY
        value: "P2P" # VPN Type
      - name: LOCAL_NETWORK
        value: "192.168.188.0/24"
      - name: TRANSMISSION_PEER_PORT
        value: "47444"
      - name: TRANSMISSION_DOWNLOAD_DIR
        value: "/downloads/transmission"
      - name: TRANSMISSION_RPC_AUTHENTICATION_REQUIRED
        value: "true"
      - name: TRANSMISSION_DOWNLOAD_QUEUE_SIZE
        value: "8"
      - name: PUID
        value: "1000"
      - name: PGID
        value: "1000"
    envFrom:
      - secretRef:
          name: transmission
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
#          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
#          external-dns/is-public: "true"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          cert-manager.io/issue-temporary-certificate: "true"
#            hajimari.io/enable: "true"
#            hajimari.io/icon: "shield-key"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: download.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - download.${SECRET_DOMAIN}
            secretName: "download-tls"
    persistence:
      data:
        enabled: true
        existingClaim: "filebrowser-media-v1"
