---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - config-pvc.yaml
  - helm-release.yaml
  - media-pvc.yaml
  - openvpn-auth.sops.yaml
  - openvpn-config.sops.yaml
  - secrets.sops.yaml
