---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
  namespace: default
  labels:
#    kasten.io/backup-volume: "enabled"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 931.5Gi
  storageClassName: openebs-device
