---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
  namespace: default
  labels:
#    kasten.io/backup-volume: "enabled"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: openebs-device
