apiVersion: v1
kind: Secret
metadata:
    name: transmission
    namespace: default
stringData:
    TRANSMISSION_RPC_USERNAME: ENC[AES256_GCM,data:z//HDtqIOA==,iv:XQtOJuR66rUEo+mddi6XIDl8q+Tr8vC95hJvZSdBWH8=,tag:dTRdjfSdjo8/soPx0wyebg==,type:str]
    TRANSMISSION_RPC_PASSWORD: ENC[AES256_GCM,data:GnvgR/oxwEfRA7PtLRw=,iv:125vsPll1ytbz6nHtVQ5XmHfVG2dAaUX/c7MIaQTlm0=,tag:EOa4qNqQkdOSUmRz1qJ8Nw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-08T13:06:03Z"
    mac: ENC[AES256_GCM,data:rrnc5TNniwzojEiUz7a+xcNM8OOhnnnTs2v3/480bHD6AEpQqLofZTES7BPvpNHMMnJKjoHe7beuGT3tixTV0q5erEuk7FMRyTg6HIVXyn56HN/aqnjnvZbSMZmqDhmvvlnxENOVcRe7TSfpRNcApoyqRCE4SFK8vPvRkyWqR8Q=,iv:j8yJHUXTV0mrZnmmOAfsQt8FgJZjJy2zGt/j9AskU3M=,tag:rxVX/PlhsJM4Ry76p6wIAg==,type:str]
    pgp:
        - created_at: "2021-11-08T13:06:03Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA452ft8CT80SARAAuUTFtkrABmYOpiRSe5/PwbY8eMip/QckU5xOuje7qPWp
            /4SOWdNNdbKRbs+3qczbDtePt77qltB3FFsrGY0m6OvS2iC7VznviLGt6Sew5ora
            /zarTJ9r6wyAUJcKPz6ptUQhV4SM0GLTiaK16bLzOTfcoGbGJE5+ngHZZZ/0rMmc
            6o2I2CX9hIlKdmjlrldulCbNtR5mW+HGxixWmk9LifEtYbP5TThABcsWvII9eowi
            ZIt0nJEOb2vj5hNoTBPNnW1gtraEtp1KQwQ4VsPYBib3517VqXt62TeDmofvQOLV
            f67Zjk0rUXluCAbwm9RkjRB42bG7nQfy6PBd+PU/syLXTwmVcA8FNOoD59H5mwbR
            n3Vgy57BBiJMYRrE4b4EdX+A/qXCtJXxp3dXxM3qxc8PhXswKowHQvWPGaXURfkK
            tISYLgmcGhSL3EhyNHWS5ABIA32xpTACz2GcfX9kqBgcv87DPnuEjlX8XonqZOLS
            jrKlPJgYE3lqGD/PHuq0Oy0CTF0Bj4wVpOUgJbhPv2FroS1ckdhpjS9Dpg0ycuiL
            aC2L60PVIVUJnZiT+5ItWBoswxYgBuTjIQi17MNdIbOWG/VGyyUZ11pRKmRGnnw5
            fhlxij0jpCNihMyilOFbt8BubHGkjTf7PZBYhhRG1qEXpOWwHfDeF8YXH5GhNALS
            XAHdzCQdfGkMX9LAXjSoIbD0IVIp1w/at8NIY4LJGKWlltnPm0Xy4bVwtkmTNFCk
            dieqyR//tfl5WNC63v/FHgOJHVP6FK73MAu4Py6bpX/wRjSkWVFQNVnpxNBE
            =tb3b
            -----END PGP MESSAGE-----
          fp: A46BCBE5025D400A71759E6947630974DB001607
        - created_at: "2021-11-08T13:06:03Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAzKiqMukNpUtAQ//bE37ktkXVKwwIfufaZP1RpkWD3qaEiZ9l2WsTTx03YG6
            1zpV/fH04rUcdC6RYoisK0NcPurjcCRDw7JSVW4XizwM+gYbf+4O4dbSM4GAPNKN
            zffG9NTKJXQZrYN8wmJdmkR5dZBHut8FSa6r6WsOqg7EiiLgtFhYuuk+QUyi5ik3
            GmtgVHfZywSocQchs1Tr6GP43JKyMOU+7vszVlksuYtUajxid9+9HGMCShKqN0cr
            t25lDFryRnQcU3MJOdmNQcjcDZsRtwH8krxcefBwewDh1mVhgVpvGvvIEYZUlgVF
            yCqx6pVRmiEkGbRCqQ0iL7eEPYFGxFOjCqMB2zM7uzT2us2zul6LpbFyH5CzbvQP
            2Z5G/IN3QkrwfoKwVTI9yVEUBscms0Uv4BFf8MavfgJQKndp0AIy0ITiOSKUXEHo
            7/F/OT71Na2dAATIUnr50Xg5x0UOoz8uUxZIa5VNlmPiGddp42nBTR/yUjyhzObl
            ouzF7prkr6fhU4auZX4QVyhVe4S9PetZs0+DFOPRV7E5cEyN2t1jcHoNvyJmbIuv
            3hMXLoaf0f+cg1dDea3hFUnjUIOOfGT2nH17Ql5MqHHcdfPsOCsi0lnM6RPy5Eir
            fVrYqaKLwagDG6I6kau1JkTkV2nPNp6I0RECyT1CDGaK6fxXR4JNo6p2ikkTP/7S
            XAGaymdLuz4qE0kJKxrrIaHjEZ2peuWOhR7qm4waJ6TVCDA/n3DfDkShZ72UItw8
            NeSybiAjO64KrWmZKfOQkVYPfmafaPUi/k9dVr83ILPzqwZFc7jt0roI+uTl
            =l2Fp
            -----END PGP MESSAGE-----
          fp: 416E502A845A87487EF12661331A5023FC9B89BA
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
