---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: changedetection-io
  namespace: self-hosted
spec:
  interval: 5m
  chart:
    spec:
      chart: /charts/kah-common/
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: dgtlmoon/changedetection.io
      tag: "0.40.0"

    nameOverride: changedetection-io

    env:
      BASE_URL: "https://changedetection.${SECRET_DOMAIN}"
      WEBDRIVER_URL: http://localhost:4444/wd/hub
      TZ: "Europe/Amsterdam"

    service:
      main:
        ports:
          http:
            port: 5000

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/icon: "web-sync"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          cert-manager.io/issue-temporary-certificate: "true"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "change-detection.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "change-detection.${SECRET_DOMAIN}"
            secretName: change-detection-tls

    persistence:
      config:
        enabled: true
        existingClaim: changedetection-io
        mountPath: /datastore
      cache:
        enabled: true
        type: emptyDir
        medium: Memory
        sizeLimit: 2Gi
        mountPath: /dev/shm

    resources:
      requests:
        cpu: 10m
        memory: 110M
      limits:
        cpu: 200m
        memory: 200M

    additionalContainers:
      chrome-webdriver:
        name: chrome-webdriver
        image: selenium/standalone-chrome-debug:3.141.59
        imagePullPolicy: IfNotPresent
        ports:
          - name: web
            containerPort: 4444
        volumeMounts:
          - name: cache
            mountPath: /dev/shm
        resources:
          requests:
            cpu: 10m
            memory: 183M
          limits:
            cpu: 100m
            memory: 300M

    podAnnotations:
      backup.velero.io/backup-volumes: config
