---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: changedetection-io
  namespace: self-hosted
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: openebs-nvme-0
