apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#  - blog-nginx
  - changedetection-io
  - echo-server
  - hajimari
  - littlelink
  - minio
#  - rxresume
  - syncthing
  - vaultwarden
