---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openebs
  namespace: openebs
spec:
  interval: 5m
  chart:
    spec:
      chart: openebs
      version: 3.0.2
      sourceRef:
        kind: HelmRepository
        name: openebs-charts
        namespace: flux-system
#  values:
#    configInline:
#      localpv-provisioner:
#        enabled: true
#        openebsNDM:
#          enabled: true
#      nfs-provisioner:
#        enabled: true
