---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: databases
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: 10.16.1
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      registry: quay.io
      repository: bitnami/postgresql
      tag: 10

    primary:
      podAnnotations:
        backup.velero.io/backup-volumes: "data"

    metrics:
      enabled: true
      serviceMonitor:
        enabled: true

    persistence:
      size: 5Gi
      existingClaim: postgresql


    postgresqlDatabase: "postgres"
    existingSecret: "postgresql"

    initdbScripts:
      my_init_script.sh: |
        #!/bin/sh
        set -e

        psql -U postgres -c "CREATE DATABASE bitbucket;"
        psql -U postgres -c "CREATE DATABASE bamboo;"

    # psql -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE bitbucket TO docker"
    #     CREATE USER docker;
    #     CREATE DATABASE my_project_development;
    #     GRANT ALL PRIVILEGES ON DATABASE my_project_development TO docker;
    #     CREATE DATABASE my_project_test;
    #     GRANT ALL PRIVILEGES ON DATABASE my_project_test TO docker;
    # EOSQL

    resources:
      requests:
        cpu: 10m
        memory: 110M
      limits:
        memory: 700M
