---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql
  namespace: databases
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: openebs-nvme-0
