apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:x5RwocEQlJKUt+G+aAW7ziJqY+UfrIFEYfBH0k2OoEL0bqRQXsAz3hGShtn7L0XMf0nob6Zq4+hOkQugt/0j93YDk8/imayEEDd1Mg4KsWW4QjbPRcsYf4L3B4RSvk9i8aoPZhTGSfeITv52eiFJdxre85WPlwoS,iv:WmpSwWJFm3Ak2JXyoUtmO4JGvyL9qem4wpg6lYHA57Y=,tag:k7iXgkHJfRZtgdoHfiNwjQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gpkhe6ap5xgmnrgjsc0vcxldp6g33gag3ul8ar2l5dvn32ccdunqpwdcuj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3UmV5TjJkcnNHdUNPOWhZ
            ZVdyTmNoOFFMalllRGRJeHRhQjdHZVZEWEhjCk4wRmZjK2FFSkdCU2dKWXZtQmxM
            bHYvbkhhditQRzNhemJHYTN3S0Q4TG8KLS0tIFdvRE0rNENBOWVsMmMrUDkwYjdH
            K0I4RTNQamhweVVURUxYWmxOdys2b0UKJzwIhC1T09FGlqmqhzcJBtQIngpmK2Cb
            k3Hyji5VrPkqe33hrwshrUca57XZ45HwVoq6t9Y5KuEV4au/rv+vmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-06T18:50:25Z"
    mac: ENC[AES256_GCM,data:w+sPBS68VEn2PYDwRN55HlMw52ZwmDES1DHXb/JQtRVWVz+J927LRXG6vZnT3V8dSO6yhGLIeQuNwMkimz7S9WABS5JTwuM5r+9DmZ1Lq4NgUxGpCVXZzeofO6wc2ESg3t4FbOqTUau8U4Tpz28W3V6CR4PP9X1wpDxvGFteng8=,iv:UISpgCCpkUI3sPdcPq/skw2HrcLXWwQI5UYwrKrIHXM=,tag:Cl5bSnEY+HPqtIq9KQ51Pg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
