---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-media-v1
  namespace: default
  labels:
#    kasten.io/backup-volume: "enabled"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: openebs-device
