---
name: Lint

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Generate Token
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Lint
        uses: github/super-linter/slim@v4
        env:
          GITHUB_TOKEN: "${{ steps.generate-token.outputs.token }}"
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main

          MARKDOWN_CONFIG_FILE: .markdownlint.yaml
          YAML_CONFIG_FILE: .yamllint.yaml
          KUBERNETES_KUBEVAL_OPTIONS: --ignore-missing-schemas
