---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads
  namespace: downloads
  labels:
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: openebs-ssd-0
