---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: self-hosted
spec:
  interval: 5m
  chart:
    spec:
      chart: vaultwarden
      version: 5.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/vaultwarden
      tag: v1.25.1

    env:
      DATA_FOLDER: "config"
      DOMAIN: https://vault.${SECRET_DOMAIN}
      SIGNUPS_ALLOWED: "false"
      SMTP_FROM_NAME: Vaultwarden
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_SSL: "true"
      TZ: "Europe/Amsterdam"
      WEBSOCKET_ADDRESS: 0.0.0.0
      WEBSOCKET_ENABLED: true
      WEBSOCKET_PORT: 3012

    envFrom:
      - secretRef:
          name: vaultwarden

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          cert-manager.io/issue-temporary-certificate: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "shield-key"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: vault.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
              - path: /notifications/hub
                pathType: Prefix
                service:
                  port: 3012
              - path: /notifications/hub/negotiate
                pathType: Prefix
        tls:
          - hosts:
              - vault.${SECRET_DOMAIN}
            secretName: "vault-tls"
      admin:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "networking-rfc1918@kubernetescrd"
        hosts:
          - host: vault.${SECRET_DOMAIN}
            paths:
              - path: /admin
                pathType: Prefix
        tls:
          - hosts:
              - vault.${SECRET_DOMAIN}
            secretName: "vault-tls"

    persistence:
      config:
        enabled: true
        existingClaim: vaultwarden

    resources:
      requests:
        cpu: 11m
        memory: 53M


    podAnnotations:
      backup.velero.io/backup-volumes: config
      secret.reloader.stakater.com/reload: "vaultwarden"
