apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden
    namespace: self-hosted
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:QdKFuIEHdwSFAPW6uiusA/adJ6nYy3yGEQiRgozlu0m11jf4nYN+kZB6B3EfR2aEv1DImkyV+vEW0FBiUDnmhQ==,iv:A9wergrBXUg6LXp9zdc0K3O/G2IZiV+R+OKPVApBaU8=,tag:kvoGcQ1b+bsspkDg/P1QUA==,type:str]
    SMTP_FROM: ENC[AES256_GCM,data:0uL+cLlCoFASBOjpn7MTnLU1InI=,iv:U7WMgV+xtg6kqlbXIgKqYJ4qB5FcNKh8yJkPbovN4Uw=,tag:hN4uldqTD2oZPs2qY1WT6w==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:pW3k+Vm9N8ECaSeevnQxfA==,iv:j+1YDPR0LQBwDiUCktj/As68IbMz5x/sj6I7enn/FAY=,tag:4As4zh8J0eRPewhUI2wKfg==,type:str]
    SMTP_USERNAME: ENC[AES256_GCM,data:0vHIA66kSCAyRr+aoh9rWNWEqYV3y6U=,iv:FqzxgFS+/ZpY8V3v2jrGpNVUFccVX62swlIlEwGaXZM=,tag:5XP74cAUTkc3ys+0fzriXA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gpkhe6ap5xgmnrgjsc0vcxldp6g33gag3ul8ar2l5dvn32ccdunqpwdcuj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQbzJTM1phQ2l2U2FVVVE5
            OEh4NXhMbUlBVHJEQllRbHVPdjlXZDExOUE4CnBQVVpDeHhhQzU0bE9RWUpKZ3kr
            WWMybDYyV1hBYTY3ZG8reGJ2OEdZOE0KLS0tIGNyK2NER29sWXdONjhVSkZzdmhR
            RWRZclFzdXVLd0l5SUJFZ1B0NFRTZTQKDaKPU2jnJkPndTPfV7zWhCsRD14azr8F
            wZ4N4BC9B/mUd7FVusff5cgOjD46WPXLVuyUmc0DdiSF+g8cfWWBUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-06T18:50:25Z"
    mac: ENC[AES256_GCM,data:YtVWq8gSRuQ/aTBZfchKFTct5nY7UYFn2zSc/ovqNkDrPZ1Nn5v4tUqAkiTN11dnROrdCw8wkVtp74u9dbREZTuVzXA0nyvlrcBpmbgoNx04fCSsqe6MCi4rqUVeWojXxvFIxbEz5FxB+bU1ZbR88fgqwgXyhBnPdKZI/Shm0RY=,iv:TsYhtyKq1tza5NJ2ttVpbMXD+iatmb6GSj1LKkMp0Wo=,tag:luP7OYgJ4A1GwmlQFXiWXg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
